#import "java_io_ObjectInputStream.h"
#import "java_io_ObjectOutputStream.h"
#import "java_io_Serializable.h"
#import "java_lang_Class.h"
#import "java_lang_IllegalArgumentException.h"
#import "java_lang_Math.h"
#import "java_lang_NullPointerException.h"
#import "java_lang_Object.h"
#import "java_util_Collection.h"
#import "java_util_Enumeration.h"
#import "java_util_Iterator.h"
#import "java_util_Map.h"
#import "java_util_Map_Entry.h"
#import "java_util_Set.h"
#import "java_util_concurrent_ConcurrentHashMap_EntrySet.h"
#import "java_util_concurrent_ConcurrentHashMap_HashEntry.h"
#import "java_util_concurrent_ConcurrentHashMap_KeyIterator.h"
#import "java_util_concurrent_ConcurrentHashMap_KeySet.h"
#import "java_util_concurrent_ConcurrentHashMap_Segment.h"
#import "java_util_concurrent_ConcurrentHashMap_ValueIterator.h"
#import "java_util_concurrent_ConcurrentHashMap_Values.h"
#import "java_util_concurrent_ConcurrentMap.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "java_util_concurrent_ConcurrentHashMap.h"
#import "org_xmlvm_iphone_NSObject.h"

JAVA_LONG _STATIC_java_util_concurrent_ConcurrentHashMap_serialVersionUID = 7249069246763182397;
int _STATIC_java_util_concurrent_ConcurrentHashMap_DEFAULT_INITIAL_CAPACITY = 16;
float _STATIC_java_util_concurrent_ConcurrentHashMap_DEFAULT_LOAD_FACTOR = 0.75;
int _STATIC_java_util_concurrent_ConcurrentHashMap_DEFAULT_CONCURRENCY_LEVEL = 16;
int _STATIC_java_util_concurrent_ConcurrentHashMap_MAXIMUM_CAPACITY = 1073741824;
int _STATIC_java_util_concurrent_ConcurrentHashMap_MAX_SEGMENTS = 65536;
int _STATIC_java_util_concurrent_ConcurrentHashMap_RETRIES_BEFORE_LOCK = 2;

@implementation java_util_concurrent_ConcurrentHashMap;

+ (void) initialize
{
    if (strcmp(class_getName(self), "java_util_concurrent_ConcurrentHashMap") == 0) {
    }
}

- (id) init
{
    if (self = [super init]) {
        segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE = (id) JAVA_NULL;
        _keySet_java_util_Set = (id) JAVA_NULL;
        entrySet_java_util_Set = (id) JAVA_NULL;
        _values_java_util_Collection = (id) JAVA_NULL;
    }
    return self;
}

- (void) dealloc
{
    [segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE release];
    [_keySet_java_util_Set release];
    [entrySet_java_util_Set release];
    [_values_java_util_Collection release];
    if (strcmp(object_getClassName(self), "java_util_concurrent_ConcurrentHashMap") == 0) {
        [self dealloc__];
    }
    [super dealloc];
}

+ (JAVA_LONG) _GET_serialVersionUID
{
    return _STATIC_java_util_concurrent_ConcurrentHashMap_serialVersionUID;
}

+ (void) _PUT_serialVersionUID: (JAVA_LONG) v
{
    _STATIC_java_util_concurrent_ConcurrentHashMap_serialVersionUID = v;
}

+ (int) _GET_DEFAULT_INITIAL_CAPACITY
{
    return _STATIC_java_util_concurrent_ConcurrentHashMap_DEFAULT_INITIAL_CAPACITY;
}

+ (void) _PUT_DEFAULT_INITIAL_CAPACITY: (int) v
{
    _STATIC_java_util_concurrent_ConcurrentHashMap_DEFAULT_INITIAL_CAPACITY = v;
}

+ (float) _GET_DEFAULT_LOAD_FACTOR
{
    return _STATIC_java_util_concurrent_ConcurrentHashMap_DEFAULT_LOAD_FACTOR;
}

+ (void) _PUT_DEFAULT_LOAD_FACTOR: (float) v
{
    _STATIC_java_util_concurrent_ConcurrentHashMap_DEFAULT_LOAD_FACTOR = v;
}

+ (int) _GET_DEFAULT_CONCURRENCY_LEVEL
{
    return _STATIC_java_util_concurrent_ConcurrentHashMap_DEFAULT_CONCURRENCY_LEVEL;
}

+ (void) _PUT_DEFAULT_CONCURRENCY_LEVEL: (int) v
{
    _STATIC_java_util_concurrent_ConcurrentHashMap_DEFAULT_CONCURRENCY_LEVEL = v;
}

+ (int) _GET_MAXIMUM_CAPACITY
{
    return _STATIC_java_util_concurrent_ConcurrentHashMap_MAXIMUM_CAPACITY;
}

+ (void) _PUT_MAXIMUM_CAPACITY: (int) v
{
    _STATIC_java_util_concurrent_ConcurrentHashMap_MAXIMUM_CAPACITY = v;
}

+ (int) _GET_MAX_SEGMENTS
{
    return _STATIC_java_util_concurrent_ConcurrentHashMap_MAX_SEGMENTS;
}

+ (void) _PUT_MAX_SEGMENTS: (int) v
{
    _STATIC_java_util_concurrent_ConcurrentHashMap_MAX_SEGMENTS = v;
}

+ (int) _GET_RETRIES_BEFORE_LOCK
{
    return _STATIC_java_util_concurrent_ConcurrentHashMap_RETRIES_BEFORE_LOCK;
}

+ (void) _PUT_RETRIES_BEFORE_LOCK: (int) v
{
    _STATIC_java_util_concurrent_ConcurrentHashMap_RETRIES_BEFORE_LOCK = v;
}

+ (int) hash___int :(int)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r3.i = n1;
    _r0.i = _r3.i << 15;
    _r0.i = _r0.i ^ -12931;
    _r0.i = _r0.i + _r3.i;
    _r1.i = ((unsigned int) _r0.i) >> (0x1f & ((unsigned int) 10));
    _r0.i = _r0.i ^ _r1.i;
    _r1.i = _r0.i << 3;
    _r0.i = _r0.i + _r1.i;
    _r1.i = ((unsigned int) _r0.i) >> (0x1f & ((unsigned int) 6));
    _r0.i = _r0.i ^ _r1.i;
    _r1.i = _r0.i << 2;
    _r2.i = _r0.i << 14;
    _r1.i = _r1.i + _r2.i;
    _r0.i = _r0.i + _r1.i;
    _r1.i = ((unsigned int) _r0.i) >> (0x1f & ((unsigned int) 16));
    _r0.i = _r0.i ^ _r1.i;
    return _r0.i;
}
- (java_util_concurrent_ConcurrentHashMap_Segment*) segmentFor___int :(int)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    _r3.o = self;
    _r4.i = n1;
    _r0.o = JAVA_NULL;
    [_r3.o retain];
    _r0.o = ((java_util_concurrent_ConcurrentHashMap*) _r3.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r0.o retain];
    _r1.i = ((java_util_concurrent_ConcurrentHashMap*) _r3.o)->segmentShift_int;
    _r1.i = ((unsigned int) _r4.i) >> (0x1f & ((unsigned int) _r1.i));
    _r2.i = ((java_util_concurrent_ConcurrentHashMap*) _r3.o)->segmentMask_int;
    _r1.i = _r1.i & _r2.i;
    _rtmp.o =  _r0.o;
    _r0.o = ((XMLVMArray*) _r0.o)->array.o[_r1.i];
    [_r0.o retain];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r3.o release];
    return _r0.o;
}
- (void) __init_java_util_concurrent_ConcurrentHashMap___int_float_int :(int)n1 :(float)n2 :(int)n3
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    XMLVMElem _r9;
    XMLVMElem _r10;
    XMLVMElem _r11;
    XMLVMElem _r12;
    _r6.o = self;
    _r7.i = n1;
    _r8.f = n2;
    _r9.i = n3;
    _r0.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    [_r6.o retain];
    _r5.i = 1073741824;
    _r1.i = 65536;
    _r4.i = 0;
    _r12.i = 1;
    [((java_util_AbstractMap*) _r6.o) __init_java_util_AbstractMap__];
    _r10.f = 0.0;
    _r10.i = _r8.f > _r10.f ? 1 : (_r8.f == _r10.f ? 0 : -1);
    if (_r10.i <= 0) goto label18;
    if (_r7.i < 0) goto label18;
    if (_r9.i > 0) goto label24;
    label18:;
    _r0.o = [[java_lang_IllegalArgumentException alloc] init];
    [((java_lang_IllegalArgumentException*) _r0.o) __init_java_lang_IllegalArgumentException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label24:;
    if (_r9.i <= _r1.i) goto label90;
    _r10 = _r1;
    label27:;
    _r1 = _r12;
    _r11 = _r4;
    label29:;
    if (_r1.i >= _r10.i) goto label36;
    _r11.i = _r11.i + 1;
    _r1.i = _r1.i << 1;
    goto label29;
    label36:;
    _r10.i = 32;
    _r10.i = _r10.i - _r11.i;
    ((java_util_concurrent_ConcurrentHashMap*) _r6.o)->segmentShift_int = _r10.i;
    _r10.i = _r1.i - _r12.i;
    ((java_util_concurrent_ConcurrentHashMap*) _r6.o)->segmentMask_int = _r10.i;
    [_r0.o release];
    _r0.o = [java_util_concurrent_ConcurrentHashMap_Segment newArray___int:_r1.i];
    [((java_util_concurrent_ConcurrentHashMap*) _r6.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE release];
    ((java_util_concurrent_ConcurrentHashMap*) _r6.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE = _r0.o;
    [_r0.o retain];
    if (_r7.i <= _r5.i) goto label88;
    _r10 = _r5;
    label54:;
    _r11.i = _r10.i / _r1.i;
    _r1.i = _r1.i * _r11.i;
    if (_r1.i >= _r10.i) goto label86;
    _r10.i = _r11.i + 1;
    label61:;
    _r1 = _r12;
    label62:;
    if (_r1.i >= _r10.i) goto label67;
    _r1.i = _r1.i << 1;
    goto label62;
    label67:;
    _r10 = _r4;
    label68:;
    [_r2.o release];
    _r2.o = ((java_util_concurrent_ConcurrentHashMap*) _r6.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r2.o retain];
    _r11.i = [_r2.o count];
    if (_r10.i >= _r11.i) goto label85;
    [_r2.o release];
    _r2.o = ((java_util_concurrent_ConcurrentHashMap*) _r6.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r2.o retain];
    [_r3.o release];
    _r3.o = [[java_util_concurrent_ConcurrentHashMap_Segment alloc] init];
    [((java_util_concurrent_ConcurrentHashMap_Segment*) _r3.o) __init_java_util_concurrent_ConcurrentHashMap_Segment___int_float:_r1.i:_r8.f];
    [((XMLVMArray*) _r2.o)->array.o[_r10.i] release];
    ((XMLVMArray*) _r2.o)->array.o[_r10.i] = _r3.o;
    [_r3.o retain];
    _r10.i = _r10.i + 1;
    goto label68;
    label85:;
    [_r0.o release];
    [_r2.o release];
    [_r3.o release];
    [_r6.o release];
    [_ex release];
    return;
    label86:;
    _r10 = _r11;
    goto label61;
    label88:;
    _r10 = _r7;
    goto label54;
    label90:;
    _r10 = _r9;
    goto label27;
}
- (void) __init_java_util_concurrent_ConcurrentHashMap___int_float :(int)n1 :(float)n2
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r1.o = self;
    _r2.i = n1;
    _r3.f = n2;
    [_r1.o retain];
    _r0.i = 16;
    [((java_util_concurrent_ConcurrentHashMap*) _r1.o) __init_java_util_concurrent_ConcurrentHashMap___int_float_int:_r2.i:_r3.f:_r0.i];
    [_r1.o release];
    return;
}
- (void) __init_java_util_concurrent_ConcurrentHashMap___int :(int)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r2.o = self;
    _r3.i = n1;
    [_r2.o retain];
    _r0.f = 0.75;
    _r1.i = 16;
    [((java_util_concurrent_ConcurrentHashMap*) _r2.o) __init_java_util_concurrent_ConcurrentHashMap___int_float_int:_r3.i:_r0.f:_r1.i];
    [_r2.o release];
    return;
}
- (void) __init_java_util_concurrent_ConcurrentHashMap__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r2.o = self;
    [_r2.o retain];
    _r1.i = 16;
    _r0.f = 0.75;
    [((java_util_concurrent_ConcurrentHashMap*) _r2.o) __init_java_util_concurrent_ConcurrentHashMap___int_float_int:_r1.i:_r0.f:_r1.i];
    [_r2.o release];
    return;
}
- (void) __init_java_util_concurrent_ConcurrentHashMap___java_util_Map :(java_util_Map*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    _r3.o = self;
    _r4.o = n1;
    [_r3.o retain];
    [_r4.o retain];
    _r2.i = 16;
    _r1.f = 0.75;
    _r0.i = [((java_util_Map*) _r4.o) size__];
    _r0.f = (float) _r0.i;
    _r0.f = _r0.f / _r1.f;
    _r0.i = (int) _r0.f;
    _r0.i = _r0.i + 1;
    _r0.i = [java_lang_Math max___int_int:_r0.i:_r2.i];
    [((java_util_concurrent_ConcurrentHashMap*) _r3.o) __init_java_util_concurrent_ConcurrentHashMap___int_float_int:_r0.i:_r1.f:_r2.i];
    [((java_util_concurrent_ConcurrentHashMap*) _r3.o) putAll___java_util_Map:_r4.o];
    [_r3.o release];
    [_r4.o release];
    return;
}
- (int) isEmpty__
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    _r6.o = self;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    _r4.o = JAVA_NULL;
    [_r6.o retain];
    _r5.i = 0;
    _r0.o = ((java_util_concurrent_ConcurrentHashMap*) _r6.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r0.o retain];
    _r1.i = [_r0.o count];
    _r1.o = [XMLVMArray createSingleDimensionWithType:5 andSize:_r1.i];
    _r2 = _r5;
    _r3 = _r5;
    label8:;
    _r4.i = [_r0.o count];
    if (_r2.i >= _r4.i) goto label29;
    _r4.o = ((XMLVMArray*) _r0.o)->array.o[_r2.i];
    [_r4.o retain];
    _rtmp.o =  _r4.o;
    _r4.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r4.o)->count_int;
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    if (_r4.i == 0) goto label19;
    [_r0.o release];
    _r0 = _r5;
    label18:;
    [_r1.o release];
    [_r6.o release];
    return _r0.i;
    label19:;
    _r4.o = ((XMLVMArray*) _r0.o)->array.o[_r2.i];
    [_r4.o retain];
    _rtmp.o =  _r4.o;
    _r4.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r4.o)->modCount_int;
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    ((XMLVMArray*) _r1.o)->array.i[_r2.i] = _r4.i;
    _r3.i = _r3.i + _r4.i;
    _r2.i = _r2.i + 1;
    goto label8;
    label29:;
    if (_r3.i == 0) goto label54;
    _r2 = _r5;
    label32:;
    _r3.i = [_r0.o count];
    if (_r2.i >= _r3.i) goto label54;
    _r3.o = ((XMLVMArray*) _r0.o)->array.o[_r2.i];
    [_r3.o retain];
    _rtmp.o =  _r3.o;
    _r3.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r3.o)->count_int;
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    if (_r3.i != 0) goto label49;
    _r3.i = ((XMLVMArray*) _r1.o)->array.i[_r2.i];
    _r4.o = ((XMLVMArray*) _r0.o)->array.o[_r2.i];
    [_r4.o retain];
    _rtmp.o =  _r4.o;
    _r4.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r4.o)->modCount_int;
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    if (_r3.i == _r4.i) goto label51;
    label49:;
    [_r0.o release];
    _r0 = _r5;
    goto label18;
    label51:;
    _r2.i = _r2.i + 1;
    goto label32;
    label54:;
    [_r0.o release];
    _r0.i = 1;
    goto label18;
}
- (int) size__
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r7;
    XMLVMElem _r9;
    XMLVMElem _r11;
    XMLVMElem _r12;
    XMLVMElem _r14;
    XMLVMElem _r15;
    XMLVMElem _r16;
    _r14.o = self;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r4.o = JAVA_NULL;
    _r7.o = JAVA_NULL;
    _r9.o = JAVA_NULL;
    [_r14.o retain];
    _r12.l = 0;
    _r11.i = 0;
    _r0.o = ((java_util_concurrent_ConcurrentHashMap*) _r14.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r0.o retain];
    _r1.i = [_r0.o count];
    _r1.o = [XMLVMArray createSingleDimensionWithType:5 andSize:_r1.i];
    _r15 = _r11;
    _r3 = _r12;
    _r5 = _r12;
    label11:;
    _r7.i = 2;
    if (_r15.i >= _r7.i) goto label133;
    _r3 = _r11;
    _r16 = _r11;
    _r5 = _r12;
    label17:;
    _r7.i = [_r0.o count];
    if (_r3.i >= _r7.i) goto label36;
    _r7.o = ((XMLVMArray*) _r0.o)->array.o[_r3.i];
    [_r7.o retain];
    _rtmp.o =  _r7.o;
    _r7.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r7.o)->count_int;
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r7.l = (JAVA_LONG) _r7.i;
    _r5.l = _r5.l + _r7.l;
    _r7.o = ((XMLVMArray*) _r0.o)->array.o[_r3.i];
    [_r7.o retain];
    _rtmp.o =  _r7.o;
    _r7.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r7.o)->modCount_int;
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    ((XMLVMArray*) _r1.o)->array.i[_r3.i] = _r7.i;
    _r16.i = _r16.i + _r7.i;
    _r3.i = _r3.i + 1;
    goto label17;
    label36:;
    if (_r16.i == 0) goto label131;
    _r3 = _r11;
    _r7 = _r12;
    label40:;
    _r16.i = [_r0.o count];
    if (_r3.i >= _r16.i) goto label129;
    [_r4.o release];
    _r4.o = ((XMLVMArray*) _r0.o)->array.o[_r3.i];
    [_r4.o retain];
    _r16.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r4.o)->count_int;
    _r9.l = (JAVA_LONG) _r16.i;
    _r7.l = _r7.l + _r9.l;
    _r16.i = ((XMLVMArray*) _r1.o)->array.i[_r3.i];
    _r9.o = ((XMLVMArray*) _r0.o)->array.o[_r3.i];
    [_r9.o retain];
    _rtmp.o =  _r9.o;
    _r9.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r9.o)->modCount_int;
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    if (_r16.i == _r9.i) goto label81;
    _r3.l = -1;
    label59:;
    _r7.i = _r3.l > _r5.l ? 1 : (_r3.l == _r5.l ? 0 : -1);
    if (_r7.i != 0) goto label84;
    [_r1.o release];
    _r1 = _r3;
    _r3 = _r5;
    label65:;
    _r1.i = _r1.l > _r3.l ? 1 : (_r1.l == _r3.l ? 0 : -1);
    if (_r1.i == 0) goto label127;
    _r1 = _r11;
    label70:;
    _r15.i = [_r0.o count];
    if (_r1.i >= _r15.i) goto label87;
    [_r2.o release];
    _r2.o = ((XMLVMArray*) _r0.o)->array.o[_r1.i];
    [_r2.o retain];
    [((java_util_concurrent_ConcurrentHashMap_Segment*) _r2.o) lock__];
    _r1.i = _r1.i + 1;
    goto label70;
    label81:;
    _r3.i = _r3.i + 1;
    goto label40;
    label84:;
    _r15.i = _r15.i + 1;
    goto label11;
    label87:;
    _r1 = _r11;
    _r15 = _r12;
    label89:;
    _r16.i = [_r0.o count];
    if (_r1.i >= _r16.i) goto label101;
    [_r4.o release];
    _r4.o = ((XMLVMArray*) _r0.o)->array.o[_r1.i];
    [_r4.o retain];
    _r16.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r4.o)->count_int;
    _r16.l = (JAVA_LONG) _r16.i;
    _r15.l = _r15.l + _r16.l;
    _r1.i = _r1.i + 1;
    goto label89;
    label101:;
    _r1 = _r11;
    label102:;
    _r16.i = [_r0.o count];
    if (_r1.i >= _r16.i) goto label113;
    [_r4.o release];
    _r4.o = ((XMLVMArray*) _r0.o)->array.o[_r1.i];
    [_r4.o retain];
    [((java_util_concurrent_ConcurrentHashMap_Segment*) _r4.o) unlock__];
    _r1.i = _r1.i + 1;
    goto label102;
    label113:;
    [_r0.o release];
    _r0 = _r15;
    label114:;
    _r15.l = 2147483647;
    _r15.i = _r0.l > _r15.l ? 1 : (_r0.l == _r15.l ? 0 : -1);
    if (_r15.i <= 0) goto label125;
    _r0.i = 2147483647;
    label124:;
    [_r2.o release];
    [_r4.o release];
    [_r14.o release];
    return _r0.i;
    label125:;
    _r0.i = (int) _r0.l;
    goto label124;
    label127:;
    [_r0.o release];
    _r0 = _r3;
    goto label114;
    label129:;
    _r3 = _r7;
    goto label59;
    label131:;
    _r3 = _r12;
    goto label59;
    label133:;
    [_r1.o release];
    _r1 = _r3;
    _r3 = _r5;
    goto label65;
}
- (java_lang_Object*) get___java_lang_Object :(java_lang_Object*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r2.o = self;
    _r3.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r2.o retain];
    [_r3.o retain];
    _r0.i = [((java_lang_Object*) _r3.o) hashCode__];
    _r0.i = [java_util_concurrent_ConcurrentHashMap hash___int:_r0.i];
    _r1.o = [((java_util_concurrent_ConcurrentHashMap*) _r2.o) segmentFor___int:_r0.i];
    _r0.o = [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) get___java_lang_Object_int:_r3.o:_r0.i];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    return _r0.o;
}
- (int) containsKey___java_lang_Object :(java_lang_Object*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r2.o = self;
    _r3.o = n1;
    _r1.o = JAVA_NULL;
    [_r2.o retain];
    [_r3.o retain];
    _r0.i = [((java_lang_Object*) _r3.o) hashCode__];
    _r0.i = [java_util_concurrent_ConcurrentHashMap hash___int:_r0.i];
    _r1.o = [((java_util_concurrent_ConcurrentHashMap*) _r2.o) segmentFor___int:_r0.i];
    _r0.i = [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) containsKey___java_lang_Object_int:_r3.o:_r0.i];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    return _r0.i;
}
- (int) containsValue___java_lang_Object :(java_lang_Object*)n1
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    XMLVMElem _r9;
    XMLVMElem _r10;
    XMLVMElem _r11;
    XMLVMElem _r12;
    _r8.o = self;
    _r9.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    _r4.o = JAVA_NULL;
    _r5.o = JAVA_NULL;
    [_r8.o retain];
    [_r9.o retain];
    _r7.i = 1;
    _r6.i = 0;
    if (_r9.o != JAVA_NULL) goto label10;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label10:;
    [_r0.o release];
    _r0.o = ((java_util_concurrent_ConcurrentHashMap*) _r8.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r0.o retain];
    _r10.i = [_r0.o count];
    _r1.o = [XMLVMArray createSingleDimensionWithType:5 andSize:_r10.i];
    _r11 = _r6;
    label16:;
    _r12.i = 2;
    if (_r11.i >= _r12.i) goto label77;
    _r12 = _r6;
    _r4 = _r6;
    label21:;
    _r5.i = [_r0.o count];
    if (_r12.i >= _r5.i) goto label48;
    _r5.o = ((XMLVMArray*) _r0.o)->array.o[_r12.i];
    [_r5.o retain];
    _rtmp.o =  _r5.o;
    _r5.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r5.o)->count_int;
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r5.o = ((XMLVMArray*) _r0.o)->array.o[_r12.i];
    [_r5.o retain];
    _rtmp.o =  _r5.o;
    _r5.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r5.o)->modCount_int;
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    ((XMLVMArray*) _r1.o)->array.i[_r12.i] = _r5.i;
    _r4.i = _r4.i + _r5.i;
    _r5.o = ((XMLVMArray*) _r0.o)->array.o[_r12.i];
    [_r5.o retain];
    _rtmp.o =  _r5.o;
    _r5.i = [((java_util_concurrent_ConcurrentHashMap_Segment*) _r5.o) containsValue___java_lang_Object:_r9.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    if (_r5.i == 0) goto label45;
    [_r0.o release];
    _r0 = _r7;
    label44:;
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r8.o release];
    [_r9.o release];
    [_ex release];
    return _r0.i;
    label45:;
    _r12.i = _r12.i + 1;
    goto label21;
    label48:;
    if (_r4.i == 0) goto label135;
    _r12 = _r6;
    label51:;
    _r4.i = [_r0.o count];
    if (_r12.i >= _r4.i) goto label135;
    _r4.o = ((XMLVMArray*) _r0.o)->array.o[_r12.i];
    [_r4.o retain];
    _rtmp.o =  _r4.o;
    _r4.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r4.o)->count_int;
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r4.i = ((XMLVMArray*) _r1.o)->array.i[_r12.i];
    _r5.o = ((XMLVMArray*) _r0.o)->array.o[_r12.i];
    [_r5.o retain];
    _rtmp.o =  _r5.o;
    _r5.i = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r5.o)->modCount_int;
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    if (_r4.i == _r5.i) goto label71;
    _r12 = _r6;
    label67:;
    if (_r12.i == 0) goto label74;
    [_r0.o release];
    _r0 = _r6;
    goto label44;
    label71:;
    _r12.i = _r12.i + 1;
    goto label51;
    label74:;
    _r11.i = _r11.i + 1;
    goto label16;
    label77:;
    _r10 = _r6;
    label78:;
    _r11.i = [_r0.o count];
    if (_r10.i >= _r11.i) goto label89;
    [_r2.o release];
    _r2.o = ((XMLVMArray*) _r0.o)->array.o[_r10.i];
    [_r2.o retain];
    [((java_util_concurrent_ConcurrentHashMap_Segment*) _r2.o) lock__];
    _r10.i = _r10.i + 1;
    goto label78;
    label89:;
    _r10 = _r6;
    label90:;
    @try {
    _r11.i = [_r0.o count];
    if (_r10.i >= _r11.i) goto label133;
    [_r2.o release];
    _r2.o = ((XMLVMArray*) _r0.o)->array.o[_r10.i];
    [_r2.o retain];
    _r11.i = [((java_util_concurrent_ConcurrentHashMap_Segment*) _r2.o) containsValue___java_lang_Object:_r9.o];
}
    @catch (id ex) {
        _ex = ex;
        goto label117;
    }
    if (_r11.i == 0) goto label114;
    _r10 = _r7;
    label102:;
    _r11 = _r6;
    label103:;
    _r12.i = [_r0.o count];
    if (_r11.i >= _r12.i) goto label131;
    [_r3.o release];
    _r3.o = ((XMLVMArray*) _r0.o)->array.o[_r11.i];
    [_r3.o retain];
    [((java_util_concurrent_ConcurrentHashMap_Segment*) _r3.o) unlock__];
    _r11.i = _r11.i + 1;
    goto label103;
    label114:;
    _r10.i = _r10.i + 1;
    goto label90;
    label117:;
    [_r1.o release];
    _r1.o = _ex; _ex = JAVA_NULL;
    _r11 = _r6;
    label119:;
    _r12.i = [_r0.o count];
    if (_r11.i >= _r12.i) goto label130;
    [_r3.o release];
    _r3.o = ((XMLVMArray*) _r0.o)->array.o[_r11.i];
    [_r3.o retain];
    [((java_util_concurrent_ConcurrentHashMap_Segment*) _r3.o) unlock__];
    _r11.i = _r11.i + 1;
    goto label119;
    label130:;
    [_ex release];
    _ex = _r1.o;
   _r1.o = JAVA_NULL;
    @throw _ex;
      label131:;
    [_r0.o release];
    _r0 = _r10;
    goto label44;
    label133:;
    _r10 = _r6;
    goto label102;
    label135:;
    _r12 = _r7;
    goto label67;
}
- (int) contains___java_lang_Object :(java_lang_Object*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    [_r1.o retain];
    [_r2.o retain];
    _r0.i = [((java_util_concurrent_ConcurrentHashMap*) _r1.o) containsValue___java_lang_Object:_r2.o];
    [_r1.o release];
    [_r2.o release];
    return _r0.i;
}
- (java_lang_Object*) put___java_lang_Object_java_lang_Object :(java_lang_Object*)n1 :(java_lang_Object*)n2
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r3.o = self;
    _r4.o = n1;
    _r5.o = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    [_r5.o retain];
    if (_r5.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    [_r0.o release];
    _r0.i = [((java_lang_Object*) _r4.o) hashCode__];
    _r0.i = [java_util_concurrent_ConcurrentHashMap hash___int:_r0.i];
    _r1.o = [((java_util_concurrent_ConcurrentHashMap*) _r3.o) segmentFor___int:_r0.i];
    _r2.i = 0;
    _r0.o = [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) put___java_lang_Object_int_java_lang_Object_boolean:_r4.o:_r0.i:_r5.o:_r2.i];
    [_r1.o release];
    [_r3.o release];
    [_r4.o release];
    [_r5.o release];
    [_ex release];
    return _r0.o;
}
- (java_lang_Object*) putIfAbsent___java_lang_Object_java_lang_Object :(java_lang_Object*)n1 :(java_lang_Object*)n2
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r3.o = self;
    _r4.o = n1;
    _r5.o = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    [_r5.o retain];
    if (_r5.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    [_r0.o release];
    _r0.i = [((java_lang_Object*) _r4.o) hashCode__];
    _r0.i = [java_util_concurrent_ConcurrentHashMap hash___int:_r0.i];
    _r1.o = [((java_util_concurrent_ConcurrentHashMap*) _r3.o) segmentFor___int:_r0.i];
    _r2.i = 1;
    _r0.o = [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) put___java_lang_Object_int_java_lang_Object_boolean:_r4.o:_r0.i:_r5.o:_r2.i];
    [_r1.o release];
    [_r3.o release];
    [_r4.o release];
    [_r5.o release];
    [_ex release];
    return _r0.o;
}
- (void) putAll___java_util_Map :(java_util_Map*)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    _r3.o = self;
    _r4.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    _r0.o = [((java_util_Map*) _r4.o) entrySet__];
    _r1.o = [((java_util_Set*) _r0.o) iterator__];
    label8:;
    [_r0.o release];
    _r0.i = [((java_util_Iterator*) _r1.o) hasNext__];
    if (_r0.i == 0) goto label32;
    _r0.o = [((java_util_Iterator*) _r1.o) next__];
    _r0.o = _r0.o;
    [_r2.o release];
    _r2.o = [((java_util_Map_Entry*) _r0.o) getKey__];
    _rtmp.o =  _r0.o;
    _r0.o = [((java_util_Map_Entry*) _r0.o) getValue__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o = [((java_util_concurrent_ConcurrentHashMap*) _r3.o) put___java_lang_Object_java_lang_Object:_r2.o:_r0.o];
    [_rtmp.o release];
    goto label8;
    label32:;
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    return;
}
- (java_lang_Object*) remove___java_lang_Object :(java_lang_Object*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    _r3.o = self;
    _r4.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    _r0.i = [((java_lang_Object*) _r4.o) hashCode__];
    _r0.i = [java_util_concurrent_ConcurrentHashMap hash___int:_r0.i];
    _r1.o = [((java_util_concurrent_ConcurrentHashMap*) _r3.o) segmentFor___int:_r0.i];
    _r2.o = JAVA_NULL;
    _r0.o = [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) remove___java_lang_Object_int_java_lang_Object:_r4.o:_r0.i:_r2.o];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    return _r0.o;
}
- (int) remove___java_lang_Object_java_lang_Object :(java_lang_Object*)n1 :(java_lang_Object*)n2
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r3.o = self;
    _r4.o = n1;
    _r5.o = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    [_r5.o retain];
    _r2.i = 0;
    _r0.i = [((java_lang_Object*) _r4.o) hashCode__];
    _r0.i = [java_util_concurrent_ConcurrentHashMap hash___int:_r0.i];
    if (_r5.o != JAVA_NULL) goto label13;
    _r0 = _r2;
    label12:;
    [_r1.o release];
    [_r3.o release];
    [_r4.o release];
    [_r5.o release];
    return _r0.i;
    label13:;
    _r1.o = [((java_util_concurrent_ConcurrentHashMap*) _r3.o) segmentFor___int:_r0.i];
    _r0.o = [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) remove___java_lang_Object_int_java_lang_Object:_r4.o:_r0.i:_r5.o];
    if (_r0.o == JAVA_NULL) goto label25;
    [_r0.o release];
    _r0.i = 1;
    goto label12;
    label25:;
    [_r0.o release];
    _r0 = _r2;
    goto label12;
}
- (int) replace___java_lang_Object_java_lang_Object_java_lang_Object :(java_lang_Object*)n1 :(java_lang_Object*)n2 :(java_lang_Object*)n3
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r2.o = self;
    _r3.o = n1;
    _r4.o = n2;
    _r5.o = n3;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r2.o retain];
    [_r3.o retain];
    [_r4.o retain];
    [_r5.o retain];
    if (_r4.o == JAVA_NULL) goto label4;
    if (_r5.o != JAVA_NULL) goto label10;
    label4:;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label10:;
    [_r0.o release];
    _r0.i = [((java_lang_Object*) _r3.o) hashCode__];
    _r0.i = [java_util_concurrent_ConcurrentHashMap hash___int:_r0.i];
    _r1.o = [((java_util_concurrent_ConcurrentHashMap*) _r2.o) segmentFor___int:_r0.i];
    _r0.i = [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) replace___java_lang_Object_int_java_lang_Object_java_lang_Object:_r3.o:_r0.i:_r4.o:_r5.o];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    [_r5.o release];
    [_ex release];
    return _r0.i;
}
- (java_lang_Object*) replace___java_lang_Object_java_lang_Object :(java_lang_Object*)n1 :(java_lang_Object*)n2
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    _r2.o = self;
    _r3.o = n1;
    _r4.o = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r2.o retain];
    [_r3.o retain];
    [_r4.o retain];
    if (_r4.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    [_r0.o release];
    _r0.i = [((java_lang_Object*) _r3.o) hashCode__];
    _r0.i = [java_util_concurrent_ConcurrentHashMap hash___int:_r0.i];
    _r1.o = [((java_util_concurrent_ConcurrentHashMap*) _r2.o) segmentFor___int:_r0.i];
    _r0.o = [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) replace___java_lang_Object_int_java_lang_Object:_r3.o:_r0.i:_r4.o];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    [_ex release];
    return _r0.o;
}
- (void) clear__
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r2.o = self;
    _r1.o = JAVA_NULL;
    [_r2.o retain];
    _r0.i = 0;
    label1:;
    [_r1.o release];
    _r1.o = ((java_util_concurrent_ConcurrentHashMap*) _r2.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r1.o retain];
    _rtmp.o =  _r1.o;
    _r1.i = [_r1.o count];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    if (_r0.i >= _r1.i) goto label16;
    _r1.o = ((java_util_concurrent_ConcurrentHashMap*) _r2.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r1.o retain];
    _rtmp.o =  _r1.o;
    _r1.o = ((XMLVMArray*) _r1.o)->array.o[_r0.i];
    [_r1.o retain];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) clear__];
    _r0.i = _r0.i + 1;
    goto label1;
    label16:;
    [_r2.o release];
    return;
}
- (java_util_Set*) keySet__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = ((java_util_concurrent_ConcurrentHashMap*) _r1.o)->keySet_java_util_Set;
    [_r0.o retain];
    if (_r0.o == JAVA_NULL) goto label5;
    label4:;
    [_r1.o release];
    return _r0.o;
    label5:;
    [_r0.o release];
    _r0.o = [[java_util_concurrent_ConcurrentHashMap_KeySet alloc] init];
    [((java_util_concurrent_ConcurrentHashMap_KeySet*) _r0.o) __init_java_util_concurrent_ConcurrentHashMap_KeySet___java_util_concurrent_ConcurrentHashMap:_r1.o];
    [((java_util_concurrent_ConcurrentHashMap*) _r1.o)->keySet_java_util_Set release];
    ((java_util_concurrent_ConcurrentHashMap*) _r1.o)->keySet_java_util_Set = _r0.o;
    [_r0.o retain];
    goto label4;
}
- (java_util_Collection*) values__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = ((java_util_concurrent_ConcurrentHashMap*) _r1.o)->values_java_util_Collection;
    [_r0.o retain];
    if (_r0.o == JAVA_NULL) goto label5;
    label4:;
    [_r1.o release];
    return _r0.o;
    label5:;
    [_r0.o release];
    _r0.o = [[java_util_concurrent_ConcurrentHashMap_Values alloc] init];
    [((java_util_concurrent_ConcurrentHashMap_Values*) _r0.o) __init_java_util_concurrent_ConcurrentHashMap_Values___java_util_concurrent_ConcurrentHashMap:_r1.o];
    [((java_util_concurrent_ConcurrentHashMap*) _r1.o)->values_java_util_Collection release];
    ((java_util_concurrent_ConcurrentHashMap*) _r1.o)->values_java_util_Collection = _r0.o;
    [_r0.o retain];
    goto label4;
}
- (java_util_Set*) entrySet__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = ((java_util_concurrent_ConcurrentHashMap*) _r1.o)->entrySet_java_util_Set;
    [_r0.o retain];
    if (_r0.o == JAVA_NULL) goto label5;
    label4:;
    [_r1.o release];
    return _r0.o;
    label5:;
    [_r0.o release];
    _r0.o = [[java_util_concurrent_ConcurrentHashMap_EntrySet alloc] init];
    [((java_util_concurrent_ConcurrentHashMap_EntrySet*) _r0.o) __init_java_util_concurrent_ConcurrentHashMap_EntrySet___java_util_concurrent_ConcurrentHashMap:_r1.o];
    [((java_util_concurrent_ConcurrentHashMap*) _r1.o)->entrySet_java_util_Set release];
    ((java_util_concurrent_ConcurrentHashMap*) _r1.o)->entrySet_java_util_Set = _r0.o;
    [_r0.o retain];
    goto label4;
}
- (java_util_Enumeration*) keys__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = [[java_util_concurrent_ConcurrentHashMap_KeyIterator alloc] init];
    [((java_util_concurrent_ConcurrentHashMap_KeyIterator*) _r0.o) __init_java_util_concurrent_ConcurrentHashMap_KeyIterator___java_util_concurrent_ConcurrentHashMap:_r1.o];
    [_r1.o release];
    return _r0.o;
}
- (java_util_Enumeration*) elements__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = [[java_util_concurrent_ConcurrentHashMap_ValueIterator alloc] init];
    [((java_util_concurrent_ConcurrentHashMap_ValueIterator*) _r0.o) __init_java_util_concurrent_ConcurrentHashMap_ValueIterator___java_util_concurrent_ConcurrentHashMap:_r1.o];
    [_r1.o release];
    return _r0.o;
}
- (void) writeObject___java_io_ObjectOutputStream :(java_io_ObjectOutputStream*)n1
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    XMLVMElem _r9;
    XMLVMElem _r10;
    XMLVMElem _r11;
    XMLVMElem _r12;
    _r8.o = self;
    _r9.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r4.o = JAVA_NULL;
    _r5.o = JAVA_NULL;
    _r7.o = JAVA_NULL;
    [_r8.o retain];
    [_r9.o retain];
    _r7.o = JAVA_NULL;
    _r6.i = 0;
    [((java_io_ObjectOutputStream*) _r9.o) defaultWriteObject__];
    _r10 = _r6;
    label6:;
    [_r1.o release];
    _r1.o = ((java_util_concurrent_ConcurrentHashMap*) _r8.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r1.o retain];
    _r11.i = [_r1.o count];
    if (_r10.i >= _r11.i) goto label55;
    [_r1.o release];
    _r1.o = ((java_util_concurrent_ConcurrentHashMap*) _r8.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r1.o retain];
    _rtmp.o =  _r1.o;
    _r1.o = ((XMLVMArray*) _r1.o)->array.o[_r10.i];
    [_r1.o retain];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) lock__];
    @try {
    [_r2.o release];
    _r2.o = ((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o)->table_java_util_concurrent_ConcurrentHashMap_HashEntry_ARRAYTYPE;
    [_r2.o retain];
    _r3 = _r6;
}
    @catch (id ex) {
        _ex = ex;
        goto label50;
    }
    label21:;
    @try {
    _r12.i = [_r2.o count];
    if (_r3.i >= _r12.i) goto label44;
    [_r4.o release];
    _r4.o = ((XMLVMArray*) _r2.o)->array.o[_r3.i];
    [_r4.o retain];
}
    @catch (id ex) {
        _ex = ex;
        goto label50;
    }
    label26:;
    @try {
    if (_r4.o == JAVA_NULL) goto label41;
    [_r5.o release];
    _r5.o = ((java_util_concurrent_ConcurrentHashMap_HashEntry*) _r4.o)->key_java_lang_Object;
    [_r5.o retain];
    [((java_io_ObjectOutputStream*) _r9.o) writeObject___java_lang_Object:_r5.o];
    [_r5.o release];
    _r5.o = ((java_util_concurrent_ConcurrentHashMap_HashEntry*) _r4.o)->value_java_lang_Object;
    [_r5.o retain];
    [((java_io_ObjectOutputStream*) _r9.o) writeObject___java_lang_Object:_r5.o];
    _rtmp.o =  _r4.o;
    _r4.o = ((java_util_concurrent_ConcurrentHashMap_HashEntry*) _r4.o)->next_java_util_concurrent_ConcurrentHashMap_HashEntry;
    [_r4.o retain];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
}
    @catch (id ex) {
        _ex = ex;
        goto label50;
    }
    goto label26;
    label41:;
    _r3.i = _r3.i + 1;
    goto label21;
    label44:;
    [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) unlock__];
    _r10.i = _r10.i + 1;
    goto label6;
    label50:;
    _r0.o = _ex; _ex = JAVA_NULL;
    [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) unlock__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label55:;
    [((java_io_ObjectOutputStream*) _r9.o) writeObject___java_lang_Object:_r7.o];
    [((java_io_ObjectOutputStream*) _r9.o) writeObject___java_lang_Object:_r7.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r4.o release];
    [_r5.o release];
    [_r7.o release];
    [_r8.o release];
    [_r9.o release];
    [_ex release];
    return;
}
- (void) readObject___java_io_ObjectInputStream :(java_io_ObjectInputStream*)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    _r3.o = self;
    _r4.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    [((java_io_ObjectInputStream*) _r4.o) defaultReadObject__];
    _r5.i = 0;
    label4:;
    [_r1.o release];
    _r1.o = ((java_util_concurrent_ConcurrentHashMap*) _r3.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r1.o retain];
    _r6.i = [_r1.o count];
    if (_r5.i >= _r6.i) goto label25;
    [_r1.o release];
    _r1.o = ((java_util_concurrent_ConcurrentHashMap*) _r3.o)->segments_java_util_concurrent_ConcurrentHashMap_Segment_ARRAYTYPE;
    [_r1.o retain];
    _rtmp.o =  _r1.o;
    _r1.o = ((XMLVMArray*) _r1.o)->array.o[_r5.i];
    [_r1.o retain];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r2.o release];
    _r2.i = 1;
    _r2.o = [XMLVMArray createSingleDimensionWithType:0 andSize:_r2.i];
    [((java_util_concurrent_ConcurrentHashMap_Segment*) _r1.o) setTable___java_util_concurrent_ConcurrentHashMap_HashEntry_ARRAYTYPE:_r2.o];
    _r5.i = _r5.i + 1;
    goto label4;
    label22:;
    _rtmp.o = [((java_util_concurrent_ConcurrentHashMap*) _r3.o) put___java_lang_Object_java_lang_Object:_r0.o:_r1.o];
    [_rtmp.o release];
    label25:;
    [_r0.o release];
    _r0.o = [((java_io_ObjectInputStream*) _r4.o) readObject__];
    [_r1.o release];
    _r1.o = [((java_io_ObjectInputStream*) _r4.o) readObject__];
    if (_r0.o != JAVA_NULL) goto label22;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    return;
}

@end

