#import "java_io_Bits.h"
#import "java_io_ObjectStreamField.h"
#import "java_lang_Class.h"
#import "java_lang_ClassCastException.h"
#import "java_lang_InternalError.h"
#import "java_lang_NullPointerException.h"
#import "java_lang_String.h"
#import "java_lang_StringBuilder.h"
#import "java_lang_reflect_Field.h"
#import "java_util_ArrayList.h"
#import "sun_misc_Unsafe.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "java_io_ObjectStreamClass_FieldReflector.h"
#import "org_xmlvm_iphone_NSObject.h"

sun_misc_Unsafe* _STATIC_java_io_ObjectStreamClass_FieldReflector_unsafe;

@implementation java_io_ObjectStreamClass_FieldReflector;

+ (void) initialize
{
    if (strcmp(class_getName(self), "java_io_ObjectStreamClass_FieldReflector") == 0) {
        _STATIC_java_io_ObjectStreamClass_FieldReflector_unsafe = (id) JAVA_NULL;
        [java_io_ObjectStreamClass_FieldReflector __clinit_java_io_ObjectStreamClass_FieldReflector];
    }
}

- (id) init
{
    if (self = [super init]) {
        fields_java_io_ObjectStreamField_ARRAYTYPE = (id) JAVA_NULL;
        keys_long_ARRAYTYPE = (id) JAVA_NULL;
        offsets_int_ARRAYTYPE = (id) JAVA_NULL;
        typeCodes_char_ARRAYTYPE = (id) JAVA_NULL;
        types_java_lang_Class_ARRAYTYPE = (id) JAVA_NULL;
    }
    return self;
}

- (void) dealloc
{
    [fields_java_io_ObjectStreamField_ARRAYTYPE release];
    [keys_long_ARRAYTYPE release];
    [offsets_int_ARRAYTYPE release];
    [typeCodes_char_ARRAYTYPE release];
    [types_java_lang_Class_ARRAYTYPE release];
    if (strcmp(object_getClassName(self), "java_io_ObjectStreamClass_FieldReflector") == 0) {
        [self dealloc__];
    }
    [super dealloc];
}

+ (sun_misc_Unsafe*) _GET_unsafe
{
    return _STATIC_java_io_ObjectStreamClass_FieldReflector_unsafe;
}

+ (void) _PUT_unsafe: (sun_misc_Unsafe*) v
{
    _STATIC_java_io_ObjectStreamClass_FieldReflector_unsafe = v;
}

+ (void) _RELEASE_unsafe
{
    [_STATIC_java_io_ObjectStreamClass_FieldReflector_unsafe release];
}

- (void) __init_java_io_ObjectStreamClass_FieldReflector___java_io_ObjectStreamField_ARRAYTYPE :(XMLVMArray*)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r8;
    XMLVMElem _r9;
    XMLVMElem _r10;
    _r8.o = self;
    _r9.o = n1;
    _r0.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    _r4.o = JAVA_NULL;
    _r5.o = JAVA_NULL;
    _r6.o = JAVA_NULL;
    [_r8.o retain];
    [_r9.o retain];
    [((java_lang_Object*) _r8.o) __init_java_lang_Object__];
    [((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->fields_java_io_ObjectStreamField_ARRAYTYPE release];
    ((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->fields_java_io_ObjectStreamField_ARRAYTYPE = _r9.o;
    [_r9.o retain];
    _r1.i = [_r9.o count];
    _r0.o = [XMLVMArray createSingleDimensionWithType:8 andSize:_r1.i];
    [((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->keys_long_ARRAYTYPE release];
    ((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->keys_long_ARRAYTYPE = _r0.o;
    [_r0.o retain];
    [_r0.o release];
    _r0.o = [XMLVMArray createSingleDimensionWithType:5 andSize:_r1.i];
    [((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->offsets_int_ARRAYTYPE release];
    ((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->offsets_int_ARRAYTYPE = _r0.o;
    [_r0.o retain];
    [_r0.o release];
    _r0.o = [XMLVMArray createSingleDimensionWithType:2 andSize:_r1.i];
    [((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->typeCodes_char_ARRAYTYPE release];
    ((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->typeCodes_char_ARRAYTYPE = _r0.o;
    [_r0.o retain];
    [_r0.o release];
    _r0.o = [[java_util_ArrayList alloc] init];
    [((java_util_ArrayList*) _r0.o) __init_java_util_ArrayList__];
    _r2.i = 0;
    label24:;
    if (_r2.i >= _r1.i) goto label83;
    [_r3.o release];
    _r3.o = ((XMLVMArray*) _r9.o)->array.o[_r2.i];
    [_r3.o retain];
    [_r4.o release];
    _r4.o = [((java_io_ObjectStreamField*) _r3.o) getField__];
    [_r5.o release];
    _r5.o = ((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->keys_long_ARRAYTYPE;
    [_r5.o retain];
    if (_r4.o == JAVA_NULL) goto label78;
    _r6.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r6.o retain];
    _rtmp.o =  _r6.o;
    _r6.l = [((sun_misc_Unsafe*) _r6.o) objectFieldOffset___java_lang_reflect_Field:_r4.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    label42:;
    ((XMLVMArray*) _r5.o)->array.l[_r2.i] = _r6.l;
    [_r5.o release];
    _r5.o = ((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->offsets_int_ARRAYTYPE;
    [_r5.o retain];
    _r6.i = [((java_io_ObjectStreamField*) _r3.o) getOffset__];
    ((XMLVMArray*) _r5.o)->array.i[_r2.i] = _r6.i;
    [_r5.o release];
    _r5.o = ((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->typeCodes_char_ARRAYTYPE;
    [_r5.o retain];
    _r6.i = [((java_io_ObjectStreamField*) _r3.o) getTypeCode__];
    ((XMLVMArray*) _r5.o)->array.c[_r2.i] = _r6.i;
    _r10.i = [((java_io_ObjectStreamField*) _r3.o) isPrimitive__];
    if (_r10.i != 0) goto label75;
    if (_r4.o == JAVA_NULL) goto label81;
    [_r3.o release];
    _r3.o = [((java_lang_reflect_Field*) _r4.o) getType__];
    label72:;
    [((java_util_ArrayList*) _r0.o) add___java_lang_Object:_r3.o];
    label75:;
    _r2.i = _r2.i + 1;
    goto label24;
    label78:;
    _r6.l = -1;
    goto label42;
    label81:;
    [_r3.o release];
    _r3.o = JAVA_NULL;
    goto label72;
    label83:;
    _r2.i = [((java_util_ArrayList*) _r0.o) size__];
    _r2.o = [XMLVMArray createSingleDimensionWithType:0 andSize:_r2.i];
    _rtmp.o =  _r0.o;
    _r0.o = [((java_util_ArrayList*) _r0.o) toArray___java_lang_Object_ARRAYTYPE:_r2.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r0.o = _r0.o;
    _r0.o = _r0.o;
    [((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->types_java_lang_Class_ARRAYTYPE release];
    ((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->types_java_lang_Class_ARRAYTYPE = _r0.o;
    [_r0.o retain];
    [_r0.o release];
    _r0.o = ((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->types_java_lang_Class_ARRAYTYPE;
    [_r0.o retain];
    _rtmp.o =  _r0.o;
    _r0.i = [_r0.o count];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r0.i = _r1.i - _r0.i;
    ((java_io_ObjectStreamClass_FieldReflector*) _r8.o)->numPrimFields_int = _r0.i;
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    [_r5.o release];
    [_r8.o release];
    [_r9.o release];
    return;
}
- (XMLVMArray*) getFields__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = ((java_io_ObjectStreamClass_FieldReflector*) _r1.o)->fields_java_io_ObjectStreamField_ARRAYTYPE;
    [_r0.o retain];
    [_r1.o release];
    return _r0.o;
}
- (void) getPrimFieldValues___java_lang_Object_byte_ARRAYTYPE :(java_lang_Object*)n1 :(XMLVMArray*)n2
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    _r5.o = self;
    _r6.o = n1;
    _r7.o = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    _r4.o = JAVA_NULL;
    [_r5.o retain];
    [_r6.o retain];
    [_r7.o retain];
    if (_r6.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    _r8.i = 0;
    label9:;
    _r1.i = ((java_io_ObjectStreamClass_FieldReflector*) _r5.o)->numPrimFields_int;
    if (_r8.i >= _r1.i) goto label115;
    _r1.o = ((java_io_ObjectStreamClass_FieldReflector*) _r5.o)->keys_long_ARRAYTYPE;
    [_r1.o retain];
    _rtmp.o =  _r1.o;
    _r1.l = ((XMLVMArray*) _r1.o)->array.l[_r8.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r3.o = ((java_io_ObjectStreamClass_FieldReflector*) _r5.o)->offsets_int_ARRAYTYPE;
    [_r3.o retain];
    _rtmp.o =  _r3.o;
    _r3.i = ((XMLVMArray*) _r3.o)->array.i[_r8.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r4.o release];
    _r4.o = ((java_io_ObjectStreamClass_FieldReflector*) _r5.o)->typeCodes_char_ARRAYTYPE;
    [_r4.o retain];
    _rtmp.o =  _r4.o;
    _r4.i = ((XMLVMArray*) _r4.o)->array.c[_r8.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    switch (_r4.i) {
    case 66: goto label46;
    case 67: goto label55;
    case 68: goto label105;
    case 70: goto label85;
    case 73: goto label75;
    case 74: goto label95;
    case 83: goto label65;
    case 90: goto label34;
    }
    [_r0.o release];
    _r0.o = [[java_lang_InternalError alloc] init];
    [((java_lang_InternalError*) _r0.o) __init_java_lang_InternalError__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label34:;
    _r4.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r4.o retain];
    _r1.i = [((sun_misc_Unsafe*) _r4.o) getBoolean___java_lang_Object_long:_r6.o:_r1.l];
    [java_io_Bits putBoolean___byte_ARRAYTYPE_int_boolean:_r7.o:_r3.i:_r1.i];
    label43:;
    _r8.i = _r8.i + 1;
    goto label9;
    label46:;
    _r4.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r4.o retain];
    _r1.i = [((sun_misc_Unsafe*) _r4.o) getByte___java_lang_Object_long:_r6.o:_r1.l];
    ((XMLVMArray*) _r7.o)->array.b[_r3.i] = _r1.i;
    goto label43;
    label55:;
    _r4.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r4.o retain];
    _r1.i = [((sun_misc_Unsafe*) _r4.o) getChar___java_lang_Object_long:_r6.o:_r1.l];
    [java_io_Bits putChar___byte_ARRAYTYPE_int_char:_r7.o:_r3.i:_r1.i];
    goto label43;
    label65:;
    _r4.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r4.o retain];
    _r1.i = [((sun_misc_Unsafe*) _r4.o) getShort___java_lang_Object_long:_r6.o:_r1.l];
    [java_io_Bits putShort___byte_ARRAYTYPE_int_short:_r7.o:_r3.i:_r1.i];
    goto label43;
    label75:;
    _r4.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r4.o retain];
    _r1.i = [((sun_misc_Unsafe*) _r4.o) getInt___java_lang_Object_long:_r6.o:_r1.l];
    [java_io_Bits putInt___byte_ARRAYTYPE_int_int:_r7.o:_r3.i:_r1.i];
    goto label43;
    label85:;
    _r4.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r4.o retain];
//    _r1.f = [((sun_misc_Unsafe*) _r4.o) getFloat___java_lang_Object_long:_r6.o:_r1.l];
//    [java_io_Bits putFloat___byte_ARRAYTYPE_int_float:_r7.o:_r3.i:_r1.f];
    goto label43;
    label95:;
    _r4.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r4.o retain];
    _r1.l = [((sun_misc_Unsafe*) _r4.o) getLong___java_lang_Object_long:_r6.o:_r1.l];
    [java_io_Bits putLong___byte_ARRAYTYPE_int_long:_r7.o:_r3.i:_r1.l];
    goto label43;
    label105:;
    _r4.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r4.o retain];
//    _r1.d = [((sun_misc_Unsafe*) _r4.o) getDouble___java_lang_Object_long:_r6.o:_r1.l];
//    [java_io_Bits putDouble___byte_ARRAYTYPE_int_double:_r7.o:_r3.i:_r1.d];
    goto label43;
    label115:;
    [_r0.o release];
    [_r4.o release];
    [_r5.o release];
    [_r6.o release];
    [_r7.o release];
    [_ex release];
    return;
    label116:;
}
- (void) setPrimFieldValues___java_lang_Object_byte_ARRAYTYPE :(java_lang_Object*)n1 :(XMLVMArray*)n2
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r4;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    XMLVMElem _r9;
    XMLVMElem _r10;
    XMLVMElem _r11;
    _r7.o = self;
    _r8.o = n1;
    _r9.o = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r7.o retain];
    [_r8.o retain];
    [_r9.o retain];
    if (_r8.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    _r10.i = 0;
    _r6 = _r10;
    label10:;
    _r10.i = ((java_io_ObjectStreamClass_FieldReflector*) _r7.o)->numPrimFields_int;
    if (_r6.i >= _r10.i) goto label125;
    [_r0.o release];
    _r0.o = ((java_io_ObjectStreamClass_FieldReflector*) _r7.o)->keys_long_ARRAYTYPE;
    [_r0.o retain];
    _r2.l = ((XMLVMArray*) _r0.o)->array.l[_r6.i];
    _r10.l = -1;
    _r10.i = _r2.l > _r10.l ? 1 : (_r2.l == _r10.l ? 0 : -1);
    if (_r10.i != 0) goto label28;
    label24:;
    _r10.i = _r6.i + 1;
    _r6 = _r10;
    goto label10;
    label28:;
    [_r0.o release];
    _r0.o = ((java_io_ObjectStreamClass_FieldReflector*) _r7.o)->offsets_int_ARRAYTYPE;
    [_r0.o retain];
    _r11.i = ((XMLVMArray*) _r0.o)->array.i[_r6.i];
    [_r0.o release];
    _r0.o = ((java_io_ObjectStreamClass_FieldReflector*) _r7.o)->typeCodes_char_ARRAYTYPE;
    [_r0.o retain];
    _r10.i = ((XMLVMArray*) _r0.o)->array.c[_r6.i];
    switch (_r10.i) {
    case 66: goto label55;
    case 67: goto label63;
    case 68: goto label114;
    case 70: goto label93;
    case 73: goto label83;
    case 74: goto label103;
    case 83: goto label73;
    case 90: goto label45;
    }
    [_r0.o release];
    _r0.o = [[java_lang_InternalError alloc] init];
    [((java_lang_InternalError*) _r0.o) __init_java_lang_InternalError__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label45:;
    [_r0.o release];
    _r0.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r0.o retain];
    _r11.i = [java_io_Bits getBoolean___byte_ARRAYTYPE_int:_r9.o:_r11.i];
    [((sun_misc_Unsafe*) _r0.o) putBoolean___java_lang_Object_long_boolean:_r8.o:_r2.l:_r11.i];
    goto label24;
    label55:;
    [_r0.o release];
    _r0.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r0.o retain];
    _r11.i = ((XMLVMArray*) _r9.o)->array.b[_r11.i];
    [((sun_misc_Unsafe*) _r0.o) putByte___java_lang_Object_long_byte:_r8.o:_r2.l:_r11.i];
    goto label24;
    label63:;
    [_r0.o release];
    _r0.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r0.o retain];
    _r11.i = [java_io_Bits getChar___byte_ARRAYTYPE_int:_r9.o:_r11.i];
    [((sun_misc_Unsafe*) _r0.o) putChar___java_lang_Object_long_char:_r8.o:_r2.l:_r11.i];
    goto label24;
    label73:;
    [_r0.o release];
    _r0.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r0.o retain];
    _r11.i = [java_io_Bits getShort___byte_ARRAYTYPE_int:_r9.o:_r11.i];
    [((sun_misc_Unsafe*) _r0.o) putShort___java_lang_Object_long_short:_r8.o:_r2.l:_r11.i];
    goto label24;
    label83:;
    [_r0.o release];
    _r0.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r0.o retain];
    _r11.i = [java_io_Bits getInt___byte_ARRAYTYPE_int:_r9.o:_r11.i];
    [((sun_misc_Unsafe*) _r0.o) putInt___java_lang_Object_long_int:_r8.o:_r2.l:_r11.i];
    goto label24;
    label93:;
    [_r0.o release];
    _r0.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r0.o retain];
    _r11.f = [java_io_Bits getFloat___byte_ARRAYTYPE_int:_r9.o:_r11.i];
    [((sun_misc_Unsafe*) _r0.o) putFloat___java_lang_Object_long_float:_r8.o:_r2.l:_r11.f];
    goto label24;
    label103:;
    [_r0.o release];
    _r0.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r0.o retain];
    _r4.l = [java_io_Bits getLong___byte_ARRAYTYPE_int:_r9.o:_r11.i];
    [_r1.o release];
    _r1 = _r8;
    [_r1.o retain];
    [((sun_misc_Unsafe*) _r0.o) putLong___java_lang_Object_long_long:_r1.o:_r2.l:_r4.l];
    goto label24;
    label114:;
    [_r0.o release];
    _r0.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r0.o retain];
    _r4.d = [java_io_Bits getDouble___byte_ARRAYTYPE_int:_r9.o:_r11.i];
    [_r1.o release];
    _r1 = _r8;
    [_r1.o retain];
    [((sun_misc_Unsafe*) _r0.o) putDouble___java_lang_Object_long_double:_r1.o:_r2.l:_r4.d];
    goto label24;
    label125:;
    [_r0.o release];
    [_r1.o release];
    [_r7.o release];
    [_r8.o release];
    [_r9.o release];
    [_ex release];
    return;
    label126:;
}
- (void) getObjFieldValues___java_lang_Object_java_lang_Object_ARRAYTYPE :(java_lang_Object*)n1 :(XMLVMArray*)n2
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    _r5.o = self;
    _r6.o = n1;
    _r7.o = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    [_r5.o retain];
    [_r6.o retain];
    [_r7.o retain];
    if (_r6.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    _r8.i = ((java_io_ObjectStreamClass_FieldReflector*) _r5.o)->numPrimFields_int;
    label10:;
    _r1.o = ((java_io_ObjectStreamClass_FieldReflector*) _r5.o)->fields_java_io_ObjectStreamField_ARRAYTYPE;
    [_r1.o retain];
    _rtmp.o =  _r1.o;
    _r1.i = [_r1.o count];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    if (_r8.i >= _r1.i) goto label47;
    _r1.o = ((java_io_ObjectStreamClass_FieldReflector*) _r5.o)->typeCodes_char_ARRAYTYPE;
    [_r1.o retain];
    _rtmp.o =  _r1.o;
    _r1.i = ((XMLVMArray*) _r1.o)->array.c[_r8.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    switch (_r1.i) {
    case 76: goto label28;
    case 91: goto label28;
    }
    [_r0.o release];
    _r0.o = [[java_lang_InternalError alloc] init];
    [((java_lang_InternalError*) _r0.o) __init_java_lang_InternalError__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label28:;
    _r1.o = ((java_io_ObjectStreamClass_FieldReflector*) _r5.o)->offsets_int_ARRAYTYPE;
    [_r1.o retain];
    _rtmp.o =  _r1.o;
    _r1.i = ((XMLVMArray*) _r1.o)->array.i[_r8.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r2.o release];
    _r2.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r2.o retain];
    _r3.o = ((java_io_ObjectStreamClass_FieldReflector*) _r5.o)->keys_long_ARRAYTYPE;
    [_r3.o retain];
    _rtmp.o =  _r3.o;
    _r3.l = ((XMLVMArray*) _r3.o)->array.l[_r8.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r2.o;
    _r2.o = [((sun_misc_Unsafe*) _r2.o) getObject___java_lang_Object_long:_r6.o:_r3.l];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [((XMLVMArray*) _r7.o)->array.o[_r1.i] release];
    ((XMLVMArray*) _r7.o)->array.o[_r1.i] = _r2.o;
    [_r2.o retain];
    _r8.i = _r8.i + 1;
    goto label10;
    label47:;
    [_r0.o release];
    [_r2.o release];
    [_r5.o release];
    [_r6.o release];
    [_r7.o release];
    [_ex release];
    return;
    label48:;
}
- (void) setObjFieldValues___java_lang_Object_java_lang_Object_ARRAYTYPE :(java_lang_Object*)n1 :(XMLVMArray*)n2
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    XMLVMElem _r9;
    XMLVMElem _r10;
    XMLVMElem _r11;
    XMLVMElem _r12;
    _r6.o = self;
    _r7.o = n1;
    _r8.o = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    _r4.o = JAVA_NULL;
    [_r6.o retain];
    [_r7.o retain];
    [_r8.o retain];
    if (_r7.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    _r9.i = ((java_io_ObjectStreamClass_FieldReflector*) _r6.o)->numPrimFields_int;
    label10:;
    [_r1.o release];
    _r1.o = ((java_io_ObjectStreamClass_FieldReflector*) _r6.o)->fields_java_io_ObjectStreamField_ARRAYTYPE;
    [_r1.o retain];
    _r10.i = [_r1.o count];
    if (_r9.i >= _r10.i) goto label179;
    [_r1.o release];
    _r1.o = ((java_io_ObjectStreamClass_FieldReflector*) _r6.o)->keys_long_ARRAYTYPE;
    [_r1.o retain];
    _r10.l = ((XMLVMArray*) _r1.o)->array.l[_r9.i];
    _r11.l = -1;
    _r11.i = _r10.l > _r11.l ? 1 : (_r10.l == _r11.l ? 0 : -1);
    if (_r11.i != 0) goto label28;
    label25:;
    _r9.i = _r9.i + 1;
    goto label10;
    label28:;
    [_r3.o release];
    _r3.o = ((java_io_ObjectStreamClass_FieldReflector*) _r6.o)->typeCodes_char_ARRAYTYPE;
    [_r3.o retain];
    _r11.i = ((XMLVMArray*) _r3.o)->array.c[_r9.i];
    switch (_r11.i) {
    case 76: goto label41;
    case 91: goto label41;
    }
    [_r0.o release];
    _r0.o = [[java_lang_InternalError alloc] init];
    [((java_lang_InternalError*) _r0.o) __init_java_lang_InternalError__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label41:;
    [_r3.o release];
    _r3.o = ((java_io_ObjectStreamClass_FieldReflector*) _r6.o)->offsets_int_ARRAYTYPE;
    [_r3.o retain];
    _r11.i = ((XMLVMArray*) _r3.o)->array.i[_r9.i];
    [_r3.o release];
    _r3.o = ((XMLVMArray*) _r8.o)->array.o[_r11.i];
    [_r3.o retain];
    if (_r3.o == JAVA_NULL) goto label172;
    [_r4.o release];
    _r4.o = ((java_io_ObjectStreamClass_FieldReflector*) _r6.o)->types_java_lang_Class_ARRAYTYPE;
    [_r4.o retain];
    _r5.i = ((java_io_ObjectStreamClass_FieldReflector*) _r6.o)->numPrimFields_int;
    _r5.i = _r9.i - _r5.i;
    _rtmp.o =  _r4.o;
    _r4.o = ((XMLVMArray*) _r4.o)->array.o[_r5.i];
    [_r4.o retain];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r12.i = [((java_lang_Class*) _r4.o) isInstance___java_lang_Object:_r3.o];
    if (_r12.i != 0) goto label172;
    [_r1.o release];
    _r1.o = ((java_io_ObjectStreamClass_FieldReflector*) _r6.o)->fields_java_io_ObjectStreamField_ARRAYTYPE;
    [_r1.o retain];
    [_r0.o release];
    _r0.o = ((XMLVMArray*) _r1.o)->array.o[_r9.i];
    [_r0.o retain];
    _rtmp.o =  _r0.o;
    _r0.o = [((java_io_ObjectStreamField*) _r0.o) getField__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r1.o release];
    _r1.o = [[java_lang_ClassCastException alloc] init];
    [_r2.o release];
    _r2.o = [[java_lang_StringBuilder alloc] init];
    [((java_lang_StringBuilder*) _r2.o) __init_java_lang_StringBuilder__];
    [_r4.o release];
    _r4.o = @"cannot assign instance of ";
    _rtmp.o =  _r2.o;
    _r2.o = [((java_lang_StringBuilder*) _r2.o) append___java_lang_String:_r4.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r3.o;
    _r3.o = [((java_lang_Object*) _r3.o) getClass__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r3.o;
    _r3.o = [((java_lang_Class*) _r3.o) getName__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r2.o;
    _r2.o = [((java_lang_StringBuilder*) _r2.o) append___java_lang_String:_r3.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r3.o release];
    _r3.o = @" to field ";
    _rtmp.o =  _r2.o;
    _r2.o = [((java_lang_StringBuilder*) _r2.o) append___java_lang_String:_r3.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r3.o release];
    _r3.o = [((java_lang_reflect_Field*) _r0.o) getDeclaringClass__];
    _rtmp.o =  _r3.o;
    _r3.o = [((java_lang_Class*) _r3.o) getName__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r2.o;
    _r2.o = [((java_lang_StringBuilder*) _r2.o) append___java_lang_String:_r3.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r3.o release];
    _r3.o = @".";
    _rtmp.o =  _r2.o;
    _r2.o = [((java_lang_StringBuilder*) _r2.o) append___java_lang_String:_r3.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r3.o release];
    _r3.o = [((java_lang_reflect_Field*) _r0.o) getName__];
    _rtmp.o =  _r2.o;
    _r2.o = [((java_lang_StringBuilder*) _r2.o) append___java_lang_String:_r3.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r3.o release];
    _r3.o = @" of type ";
    _rtmp.o =  _r2.o;
    _r2.o = [((java_lang_StringBuilder*) _r2.o) append___java_lang_String:_r3.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_reflect_Field*) _r0.o) getType__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_Class*) _r0.o) getName__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_StringBuilder*) _r2.o) append___java_lang_String:_r0.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r2.o release];
    _r2.o = @" in instance of ";
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_StringBuilder*) _r0.o) append___java_lang_String:_r2.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r2.o release];
    _r2.o = [((java_lang_Object*) _r7.o) getClass__];
    _rtmp.o =  _r2.o;
    _r2.o = [((java_lang_Class*) _r2.o) getName__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_StringBuilder*) _r0.o) append___java_lang_String:_r2.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_StringBuilder*) _r0.o) toString__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [((java_lang_ClassCastException*) _r1.o) __init_java_lang_ClassCastException___java_lang_String:_r0.o];
    [_ex release];
    _ex = _r1.o;
   _r1.o = JAVA_NULL;
    @throw _ex;
      label172:;
    [_r4.o release];
    _r4.o = [java_io_ObjectStreamClass_FieldReflector _GET_unsafe];
    [_r4.o retain];
    [((sun_misc_Unsafe*) _r4.o) putObject___java_lang_Object_long_java_lang_Object:_r7.o:_r10.l:_r3.o];
    goto label25;
    label179:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    [_r6.o release];
    [_r7.o release];
    [_r8.o release];
    [_ex release];
    return;
    label180:;
}
+ (void) __clinit_java_io_ObjectStreamClass_FieldReflector
{
    XMLVMElem _r0;
    _r0.o = JAVA_NULL;
    _r0.o = [sun_misc_Unsafe getUnsafe__];
    [java_io_ObjectStreamClass_FieldReflector _RELEASE_unsafe];
    [java_io_ObjectStreamClass_FieldReflector _PUT_unsafe: _r0.o];
    [_r0.o retain];
    [_r0.o release];
    return;
}

@end

