#import "java_io_InputStream.h"
#import "java_lang_Class.h"
#import "java_lang_Package.h"
#import "java_lang_String.h"
#import "java_net_URL.h"
#import "java_nio_ByteBuffer.h"
#import "java_security_ProtectionDomain.h"
#import "java_util_Enumeration.h"
//#import "org_xmlvm_runtime_XMLVMClassLoader.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "java_lang_ClassLoader.h"
#import "org_xmlvm_iphone_NSObject.h"

java_lang_ClassLoader* _STATIC_java_lang_ClassLoader_systemClassLoader;

@implementation java_lang_ClassLoader;

+ (void) initialize
{
    if (strcmp(class_getName(self), "java_lang_ClassLoader") == 0) {
        _STATIC_java_lang_ClassLoader_systemClassLoader = (id) JAVA_NULL;
//        [java_lang_ClassLoader __clinit_java_lang_ClassLoader];
    }
}

- (id) init
{
    if (self = [super init]) {
    }
    return self;
}

- (void) dealloc
{
    if (strcmp(object_getClassName(self), "java_lang_ClassLoader") == 0) {
        [self dealloc__];
    }
    [super dealloc];
}

+ (java_lang_ClassLoader*) _GET_systemClassLoader
{
    return _STATIC_java_lang_ClassLoader_systemClassLoader;
}

+ (void) _PUT_systemClassLoader: (java_lang_ClassLoader*) v
{
    _STATIC_java_lang_ClassLoader_systemClassLoader = v;
}

+ (void) _RELEASE_systemClassLoader
{
    [_STATIC_java_lang_ClassLoader_systemClassLoader release];
}

+ (void) initializeClassLoaders__
{
    return;
}
+ (java_lang_ClassLoader*) getSystemClassLoader__
{
    XMLVMElem _r0;
    _r0.o = JAVA_NULL;
    _r0.o = [java_lang_ClassLoader _GET_systemClassLoader];
    [_r0.o retain];
    return _r0.o;
}
+ (java_net_URL*) getSystemResource___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = [java_lang_Class getClass__];
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_Class*) _r0.o) getResource___java_lang_String:_r1.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r1.o release];
    return _r0.o;
}
+ (java_util_Enumeration*) getSystemResources___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    return _r0.o;
}
+ (java_io_InputStream*) getSystemResourceAsStream___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = [java_lang_Class getClass__];
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_Class*) _r0.o) getResourceAsStream___java_lang_String:_r1.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r1.o release];
    return _r0.o;
}
- (void) __init_java_lang_ClassLoader__
{
    XMLVMElem _r0;
    _r0.o = self;
    [_r0.o retain];
    [((java_lang_Object*) _r0.o) __init_java_lang_Object__];
    [_r0.o release];
    return;
}
- (void) __init_java_lang_ClassLoader___java_lang_ClassLoader :(java_lang_ClassLoader*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r0.o = self;
    _r1.o = n1;
    [_r0.o retain];
    [_r1.o retain];
    [((java_lang_Object*) _r0.o) __init_java_lang_Object__];
    [_r0.o release];
    [_r1.o release];
    return;
}
- (java_lang_Class*) defineClass___byte_ARRAYTYPE_int_int :(XMLVMArray*)n1 :(int)n2 :(int)n3
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    _r1.o = self;
    _r2.o = n1;
    _r3.i = n2;
    _r4.i = n3;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (java_lang_Class*) defineClass___java_lang_String_byte_ARRAYTYPE_int_int :(java_lang_String*)n1 :(XMLVMArray*)n2 :(int)n3 :(int)n4
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r1.o = self;
    _r2.o = n1;
    _r3.o = n2;
    _r4.i = n3;
    _r5.i = n4;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    [_r3.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    return _r0.o;
}
- (java_lang_Class*) defineClass___java_lang_String_byte_ARRAYTYPE_int_int_java_security_ProtectionDomain :(java_lang_String*)n1 :(XMLVMArray*)n2 :(int)n3 :(int)n4 :(java_security_ProtectionDomain*)n5
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    _r1.o = self;
    _r2.o = n1;
    _r3.o = n2;
    _r4.i = n3;
    _r5.i = n4;
    _r6.o = n5;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    [_r3.o retain];
    [_r6.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r6.o release];
    return _r0.o;
}
- (java_lang_Class*) defineClass___java_lang_String_java_nio_ByteBuffer_java_security_ProtectionDomain :(java_lang_String*)n1 :(java_nio_ByteBuffer*)n2 :(java_security_ProtectionDomain*)n3
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    XMLVMElem _r9;
    _r6.o = self;
    _r7.o = n1;
    _r8.o = n2;
    _r9.o = n3;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r5.o = JAVA_NULL;
    [_r6.o retain];
    [_r7.o retain];
    [_r8.o retain];
    [_r9.o retain];
    _r0.i = [((java_nio_ByteBuffer*) _r8.o) remaining__];
    _r2.o = [XMLVMArray createSingleDimensionWithType:3 andSize:_r0.i];
    _rtmp.o = [((java_nio_ByteBuffer*) _r8.o) get___byte_ARRAYTYPE:_r2.o];
    [_rtmp.o release];
    _r3.i = 0;
    _r4.i = [_r2.o count];
    _r0 = _r6;
    [_r0.o retain];
    _r1 = _r7;
    [_r1.o retain];
    _r5 = _r9;
    [_r5.o retain];
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_ClassLoader*) _r0.o) defineClass___java_lang_String_byte_ARRAYTYPE_int_int_java_security_ProtectionDomain:_r1.o:_r2.o:_r3.i:_r4.i:_r5.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    [_r5.o release];
    [_r6.o release];
    [_r7.o release];
    [_r8.o release];
    [_r9.o release];
    return _r0.o;
}
- (java_lang_Class*) findClass___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (java_lang_Class*) findLoadedClass___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (java_lang_Class*) findSystemClass___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (java_lang_ClassLoader*) getParent__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    return _r0.o;
}
- (java_net_URL*) getResource___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = [java_lang_Class getClass__];
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_Class*) _r0.o) getResource___java_lang_String:_r2.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (java_util_Enumeration*) getResources___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (java_io_InputStream*) getResourceAsStream___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = [java_lang_Class getClass__];
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_Class*) _r0.o) getResourceAsStream___java_lang_String:_r2.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (java_lang_Class*) loadClass___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = [java_lang_Class forName___java_lang_String:_r2.o];
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (java_lang_Class*) loadClass___java_lang_String_boolean :(java_lang_String*)n1 :(int)n2
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r1.o = self;
    _r2.o = n1;
    _r3.i = n2;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = [((java_lang_ClassLoader*) _r1.o) loadClass___java_lang_String:_r2.o];
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (void) resolveClass___java_lang_Class :(java_lang_Class*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r0.o = self;
    _r1.o = n1;
    [_r0.o retain];
    [_r1.o retain];
    [_r0.o release];
    [_r1.o release];
    return;
}
- (int) isSystemClassLoader__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    [_r1.o retain];
    _r0.i = 0;
    [_r1.o release];
    return _r0.i;
}
- (int) isAncestorOf___java_lang_ClassLoader :(java_lang_ClassLoader*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    [_r1.o retain];
    [_r2.o retain];
    _r0.i = 0;
    [_r1.o release];
    [_r2.o release];
    return _r0.i;
}
- (java_net_URL*) findResource___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = [java_lang_Class getClass__];
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_Class*) _r0.o) getResource___java_lang_String:_r2.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (java_util_Enumeration*) findResources___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (java_lang_String*) findLibrary___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (java_lang_Package*) getPackage___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (XMLVMArray*) getPackages__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    return _r0.o;
}
- (java_lang_Package*) definePackage___java_lang_String_java_lang_String_java_lang_String_java_lang_String_java_lang_String_java_lang_String_java_lang_String_java_net_URL :(java_lang_String*)n1 :(java_lang_String*)n2 :(java_lang_String*)n3 :(java_lang_String*)n4 :(java_lang_String*)n5 :(java_lang_String*)n6 :(java_lang_String*)n7 :(java_net_URL*)n8
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    XMLVMElem _r9;
    _r1.o = self;
    _r2.o = n1;
    _r3.o = n2;
    _r4.o = n3;
    _r5.o = n4;
    _r6.o = n5;
    _r7.o = n6;
    _r8.o = n7;
    _r9.o = n8;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    [_r3.o retain];
    [_r4.o retain];
    [_r5.o retain];
    [_r6.o retain];
    [_r7.o retain];
    [_r8.o retain];
    [_r9.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    [_r5.o release];
    [_r6.o release];
    [_r7.o release];
    [_r8.o release];
    [_r9.o release];
    return _r0.o;
}
- (XMLVMArray*) getSigners___java_lang_Class :(java_lang_Class*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    [_r2.o release];
    return _r0.o;
}
- (void) setSigners___java_lang_Class_java_lang_Object_ARRAYTYPE :(java_lang_Class*)n1 :(XMLVMArray*)n2
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r0.o = self;
    _r1.o = n1;
    _r2.o = n2;
    [_r0.o retain];
    [_r1.o retain];
    [_r2.o retain];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    return;
}
+ (java_lang_ClassLoader*) getStackClassLoader___int :(int)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.i = n1;
    _r0.o = JAVA_NULL;
    _r0.o = JAVA_NULL;
    return _r0.o;
}
+ (java_lang_ClassLoader*) callerClassLoader__
{
    XMLVMElem _r0;
    _r0.o = JAVA_NULL;
    _r0.o = JAVA_NULL;
    return _r0.o;
}
+ (void) loadLibraryWithClassLoader___java_lang_String_java_lang_ClassLoader :(java_lang_String*)n1 :(java_lang_ClassLoader*)n2
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r0.o = n1;
    _r1.o = n2;
    [_r0.o retain];
    [_r1.o retain];
    [_r0.o release];
    [_r1.o release];
    return;
}
+ (void) loadLibraryWithPath___java_lang_String_java_lang_ClassLoader_java_lang_String :(java_lang_String*)n1 :(java_lang_ClassLoader*)n2 :(java_lang_String*)n3
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r0.o = n1;
    _r1.o = n2;
    _r2.o = n3;
    [_r0.o retain];
    [_r1.o retain];
    [_r2.o retain];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    return;
}
- (void) setClassAssertionStatus___java_lang_String_boolean :(java_lang_String*)n1 :(int)n2
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r0.o = self;
    _r1.o = n1;
    _r2.i = n2;
    [_r0.o retain];
    [_r1.o retain];
    [_r0.o release];
    [_r1.o release];
    return;
}
- (void) setPackageAssertionStatus___java_lang_String_boolean :(java_lang_String*)n1 :(int)n2
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r0.o = self;
    _r1.o = n1;
    _r2.i = n2;
    [_r0.o retain];
    [_r1.o retain];
    [_r0.o release];
    [_r1.o release];
    return;
}
- (void) setDefaultAssertionStatus___boolean :(int)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r0.o = self;
    _r1.i = n1;
    [_r0.o retain];
    [_r0.o release];
    return;
}
- (void) clearAssertionStatus__
{
    XMLVMElem _r0;
    _r0.o = self;
    [_r0.o retain];
    [_r0.o release];
    return;
}
- (int) getClassAssertionStatus___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    [_r1.o retain];
    [_r2.o retain];
    _r0.i = 0;
    [_r1.o release];
    [_r2.o release];
    return _r0.i;
}
- (int) getPackageAssertionStatus___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    [_r1.o retain];
    [_r2.o retain];
    _r0.i = 0;
    [_r1.o release];
    [_r2.o release];
    return _r0.i;
}
- (int) getDefaultAssertionStatus__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    [_r1.o retain];
    _r0.i = 0;
    [_r1.o release];
    return _r0.i;
}
+ (void) __clinit_java_lang_ClassLoader
{
    XMLVMElem _r0;
    _r0.o = JAVA_NULL;
    _r0.o = [[org_xmlvm_runtime_XMLVMClassLoader alloc] init];
    [((org_xmlvm_runtime_XMLVMClassLoader*) _r0.o) __init_org_xmlvm_runtime_XMLVMClassLoader__];
    [java_lang_ClassLoader _RELEASE_systemClassLoader];
    [java_lang_ClassLoader _PUT_systemClassLoader: _r0.o];
    [_r0.o retain];
    [_r0.o release];
    return;
}

@end

