#import "java_io_File.h"
#import "java_io_FileDescriptor.h"
#import "java_io_FilePermission.h"
#import "java_lang_Class.h"
#import "java_lang_ClassLoader.h"
#import "java_lang_ClassNotFoundException.h"
#import "java_lang_IllegalAccessException.h"
#import "java_lang_InstantiationException.h"
#import "java_lang_NoSuchMethodException.h"
#import "java_lang_NullPointerException.h"
#import "java_lang_RuntimePermission.h"
#import "java_lang_SecurityException.h"
#import "java_lang_String.h"
#import "java_lang_StringBuilder.h"
#import "java_lang_Thread.h"
#import "java_lang_ThreadGroup.h"
#import "java_lang_reflect_Constructor.h"
#import "java_lang_reflect_InvocationTargetException.h"
#import "java_net_InetAddress.h"
#import "java_net_SocketPermission.h"
#import "java_security_AccessControlContext.h"
#import "java_security_AccessController.h"
#import "java_security_Permission.h"
#import "java_security_PrivilegedAction.h"
#import "java_security_SecurityPermission.h"
#import "java_util_PropertyPermission.h"
//#import "org_apache_harmony_luni_util_PriviAction.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "java_lang_SecurityManager.h"
#import "org_xmlvm_iphone_NSObject.h"

java_util_PropertyPermission* _STATIC_java_lang_SecurityManager_READ_WRITE_ALL_PROPERTIES_PERMISSION;
java_lang_String* _STATIC_java_lang_SecurityManager_PKG_ACC_KEY = @"package.access";
java_lang_String* _STATIC_java_lang_SecurityManager_PKG_DEF_KEY = @"package.definition";

@implementation java_lang_SecurityManager;

+ (void) initialize
{
    if (strcmp(class_getName(self), "java_lang_SecurityManager") == 0) {
        _STATIC_java_lang_SecurityManager_READ_WRITE_ALL_PROPERTIES_PERMISSION = (id) JAVA_NULL;
        _STATIC_java_lang_SecurityManager_PKG_ACC_KEY = (id) JAVA_NULL;
        _STATIC_java_lang_SecurityManager_PKG_DEF_KEY = (id) JAVA_NULL;
        [java_lang_SecurityManager __clinit_java_lang_SecurityManager];
    }
}

- (id) init
{
    if (self = [super init]) {
    }
    return self;
}

- (void) dealloc
{
    if (strcmp(object_getClassName(self), "java_lang_SecurityManager") == 0) {
        [self dealloc__];
    }
    [super dealloc];
}

+ (java_util_PropertyPermission*) _GET_READ_WRITE_ALL_PROPERTIES_PERMISSION
{
    return _STATIC_java_lang_SecurityManager_READ_WRITE_ALL_PROPERTIES_PERMISSION;
}

+ (void) _PUT_READ_WRITE_ALL_PROPERTIES_PERMISSION: (java_util_PropertyPermission*) v
{
    _STATIC_java_lang_SecurityManager_READ_WRITE_ALL_PROPERTIES_PERMISSION = v;
}

+ (void) _RELEASE_READ_WRITE_ALL_PROPERTIES_PERMISSION
{
    [_STATIC_java_lang_SecurityManager_READ_WRITE_ALL_PROPERTIES_PERMISSION release];
}

+ (java_lang_String*) _GET_PKG_ACC_KEY
{
    return _STATIC_java_lang_SecurityManager_PKG_ACC_KEY;
}

+ (void) _PUT_PKG_ACC_KEY: (java_lang_String*) v
{
    _STATIC_java_lang_SecurityManager_PKG_ACC_KEY = v;
}

+ (void) _RELEASE_PKG_ACC_KEY
{
    [_STATIC_java_lang_SecurityManager_PKG_ACC_KEY release];
}

+ (java_lang_String*) _GET_PKG_DEF_KEY
{
    return _STATIC_java_lang_SecurityManager_PKG_DEF_KEY;
}

+ (void) _PUT_PKG_DEF_KEY: (java_lang_String*) v
{
    _STATIC_java_lang_SecurityManager_PKG_DEF_KEY = v;
}

+ (void) _RELEASE_PKG_DEF_KEY
{
    [_STATIC_java_lang_SecurityManager_PKG_DEF_KEY release];
}

- (void) __init_java_lang_SecurityManager__
{
    XMLVMElem _r0;
    _r0.o = self;
    [_r0.o retain];
    [((java_lang_Object*) _r0.o) __init_java_lang_Object__];
    [_r0.o release];
    return;
}
- (void) checkAccept___java_lang_String_int :(java_lang_String*)n1 :(int)n2
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r3.o = self;
    _r4.o = n1;
    _r5.i = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    if (_r4.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    [_r0.o release];
    _r0.o = [[java_net_SocketPermission alloc] init];
    _r1.o = [[java_lang_StringBuilder alloc] init];
    [((java_lang_StringBuilder*) _r1.o) __init_java_lang_StringBuilder__];
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___java_lang_String:_r4.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r2.i = 58;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___char:_r2.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___int:_r5.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) toString__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r2.o = @"accept";
    [((java_net_SocketPermission*) _r0.o) __init_java_net_SocketPermission___java_lang_String_java_lang_String:_r1.o:_r2.o];
    [((java_lang_SecurityManager*) _r3.o) checkPermission___java_security_Permission:_r0.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    [_ex release];
    return;
}
- (void) checkAccess___java_lang_Thread :(java_lang_Thread*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r0.o = self;
    _r1.o = n1;
    [_r0.o retain];
    [_r1.o retain];
    [_r0.o release];
    [_r1.o release];
    return;
}
- (void) checkAccess___java_lang_ThreadGroup :(java_lang_ThreadGroup*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r0.o = self;
    _r1.o = n1;
    [_r0.o retain];
    [_r1.o retain];
    [_r0.o release];
    [_r1.o release];
    return;
}
- (void) checkConnect___java_lang_String_int :(java_lang_String*)n1 :(int)n2
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r3.o = self;
    _r4.o = n1;
    _r5.i = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    if (_r4.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    if (_r5.i <= 0) goto label44;
    [_r0.o release];
    _r0.o = [[java_net_SocketPermission alloc] init];
    _r1.o = [[java_lang_StringBuilder alloc] init];
    [((java_lang_StringBuilder*) _r1.o) __init_java_lang_StringBuilder__];
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___java_lang_String:_r4.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r2.i = 58;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___char:_r2.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___int:_r5.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) toString__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r2.o = @"connect";
    [((java_net_SocketPermission*) _r0.o) __init_java_net_SocketPermission___java_lang_String_java_lang_String:_r1.o:_r2.o];
    [((java_lang_SecurityManager*) _r3.o) checkPermission___java_security_Permission:_r0.o];
    label43:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    [_ex release];
    return;
    label44:;
    [_r0.o release];
    _r0.o = [[java_net_SocketPermission alloc] init];
    _r1.o = @"resolve";
    [((java_net_SocketPermission*) _r0.o) __init_java_net_SocketPermission___java_lang_String_java_lang_String:_r4.o:_r1.o];
    [((java_lang_SecurityManager*) _r3.o) checkPermission___java_security_Permission:_r0.o];
    goto label43;
}
- (void) checkConnect___java_lang_String_int_java_lang_Object :(java_lang_String*)n1 :(int)n2 :(java_lang_Object*)n3
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    _r3.o = self;
    _r4.o = n1;
    _r5.i = n2;
    _r6.o = n3;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    [_r6.o retain];
    if (_r5.i <= 0) goto label36;
    _r0.o = [[java_net_SocketPermission alloc] init];
    _r1.o = [[java_lang_StringBuilder alloc] init];
    [((java_lang_StringBuilder*) _r1.o) __init_java_lang_StringBuilder__];
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___java_lang_String:_r4.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r2.i = 58;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___char:_r2.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___int:_r5.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) toString__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _r2.o = @"connect";
    [((java_net_SocketPermission*) _r0.o) __init_java_net_SocketPermission___java_lang_String_java_lang_String:_r1.o:_r2.o];
    [((java_lang_SecurityManager*) _r3.o) checkPermission___java_security_Permission_java_lang_Object:_r0.o:_r6.o];
    label35:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    [_r6.o release];
    return;
    label36:;
    _r0.o = [[java_net_SocketPermission alloc] init];
    _r1.o = @"resolve";
    [((java_net_SocketPermission*) _r0.o) __init_java_net_SocketPermission___java_lang_String_java_lang_String:_r4.o:_r1.o];
    [((java_lang_SecurityManager*) _r3.o) checkPermission___java_security_Permission_java_lang_Object:_r0.o:_r6.o];
    goto label35;
}
- (void) checkCreateClassLoader__
{
    XMLVMElem _r0;
    _r0.o = self;
    [_r0.o retain];
    [_r0.o release];
    return;
}
- (void) checkDelete___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r2.o = self;
    _r3.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r2.o retain];
    [_r3.o retain];
    _r0.o = [[java_io_FilePermission alloc] init];
    _r1.o = @"delete";
    [((java_io_FilePermission*) _r0.o) __init_java_io_FilePermission___java_lang_String_java_lang_String:_r3.o:_r1.o];
    [((java_lang_SecurityManager*) _r2.o) checkPermission___java_security_Permission:_r0.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    return;
}
- (void) checkExec___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    _r3.o = self;
    _r4.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    _r0.o = [[java_io_FilePermission alloc] init];
    _r1.o = [[java_io_File alloc] init];
    [((java_io_File*) _r1.o) __init_java_io_File___java_lang_String:_r4.o];
    _rtmp.o =  _r1.o;
    _r1.i = [((java_io_File*) _r1.o) isAbsolute__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    if (_r1.i == 0) goto label23;
    _r1 = _r4;
    [_r1.o retain];
    label14:;
    _r2.o = @"execute";
    [((java_io_FilePermission*) _r0.o) __init_java_io_FilePermission___java_lang_String_java_lang_String:_r1.o:_r2.o];
    [((java_lang_SecurityManager*) _r3.o) checkPermission___java_security_Permission:_r0.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    return;
    label23:;
    _r1.o = @"<<ALL FILES>>";
    goto label14;
}
- (void) checkExit___int :(int)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r0.o = self;
    _r1.i = n1;
    [_r0.o retain];
    [_r0.o release];
    return;
}
- (void) checkLink___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    _r3.o = self;
    _r4.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    if (_r4.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    [_r0.o release];
    _r0.o = [[java_lang_RuntimePermission alloc] init];
    _r1.o = [[java_lang_StringBuilder alloc] init];
    [((java_lang_StringBuilder*) _r1.o) __init_java_lang_StringBuilder__];
    _r2.o = @"loadLibrary.";
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___java_lang_String:_r2.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___java_lang_String:_r4.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) toString__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [((java_lang_RuntimePermission*) _r0.o) __init_java_lang_RuntimePermission___java_lang_String:_r1.o];
    [((java_lang_SecurityManager*) _r3.o) checkPermission___java_security_Permission:_r0.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    [_ex release];
    return;
}
- (void) checkListen___int :(int)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r4.o = self;
    _r5.i = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    [_r4.o retain];
    _r3.o = @"listen";
    if (_r5.i != 0) goto label17;
    _r0.o = [[java_net_SocketPermission alloc] init];
    _r1.o = @"localhost:1024-";
    _r2.o = @"listen";
    [((java_net_SocketPermission*) _r0.o) __init_java_net_SocketPermission___java_lang_String_java_lang_String:_r1.o:_r3.o];
    [((java_lang_SecurityManager*) _r4.o) checkPermission___java_security_Permission:_r0.o];
    label16:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    return;
    label17:;
    _r0.o = [[java_net_SocketPermission alloc] init];
    _r1.o = [[java_lang_StringBuilder alloc] init];
    [((java_lang_StringBuilder*) _r1.o) __init_java_lang_StringBuilder__];
    _r2.o = @"localhost:";
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___java_lang_String:_r2.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___int:_r5.i];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) toString__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r2.o release];
    _r2.o = @"listen";
    [((java_net_SocketPermission*) _r0.o) __init_java_net_SocketPermission___java_lang_String_java_lang_String:_r1.o:_r3.o];
    [((java_lang_SecurityManager*) _r4.o) checkPermission___java_security_Permission:_r0.o];
    goto label16;
}
- (void) checkMemberAccess___java_lang_Class_int :(java_lang_Class*)n1 :(int)n2
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    _r2.o = self;
    _r3.o = n1;
    _r4.i = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r2.o retain];
    [_r3.o retain];
    if (_r3.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    if (_r4.i != 0) goto label11;
    label10:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_ex release];
    return;
    label11:;
    [_r0.o release];
    _r0.o = [[java_lang_RuntimePermission alloc] init];
    _r1.o = @"accessDeclaredMembers";
    [((java_lang_RuntimePermission*) _r0.o) __init_java_lang_RuntimePermission___java_lang_String:_r1.o];
    [((java_lang_SecurityManager*) _r2.o) checkPermission___java_security_Permission:_r0.o];
    goto label10;
}
- (void) checkMulticast___java_net_InetAddress :(java_net_InetAddress*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    _r3.o = self;
    _r4.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    _r0.o = [[java_net_SocketPermission alloc] init];
    _r1.o = [((java_net_InetAddress*) _r4.o) getHostAddress__];
    _r2.o = @"accept,connect";
    [((java_net_SocketPermission*) _r0.o) __init_java_net_SocketPermission___java_lang_String_java_lang_String:_r1.o:_r2.o];
    [((java_lang_SecurityManager*) _r3.o) checkPermission___java_security_Permission:_r0.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    return;
}
- (void) checkMulticast___java_net_InetAddress_byte :(java_net_InetAddress*)n1 :(int)n2
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r3.o = self;
    _r4.o = n1;
    _r5.i = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    _r0.o = [[java_net_SocketPermission alloc] init];
    _r1.o = [((java_net_InetAddress*) _r4.o) getHostAddress__];
    _r2.o = @"accept,connect";
    [((java_net_SocketPermission*) _r0.o) __init_java_net_SocketPermission___java_lang_String_java_lang_String:_r1.o:_r2.o];
    [((java_lang_SecurityManager*) _r3.o) checkPermission___java_security_Permission:_r0.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    return;
}
- (void) checkPackageAccess___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r3.o = self;
    _r4.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    if (_r4.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    [_r0.o release];
    _r0.o = @"package.access";
    _r5.i = [java_lang_SecurityManager checkPackageProperty___java_lang_String_java_lang_String:_r0.o:_r4.o];
    if (_r5.i == 0) goto label43;
    [_r0.o release];
    _r0.o = [[java_lang_RuntimePermission alloc] init];
    _r1.o = [[java_lang_StringBuilder alloc] init];
    [((java_lang_StringBuilder*) _r1.o) __init_java_lang_StringBuilder__];
    _r2.o = @"accessClassInPackage.";
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___java_lang_String:_r2.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___java_lang_String:_r4.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) toString__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [((java_lang_RuntimePermission*) _r0.o) __init_java_lang_RuntimePermission___java_lang_String:_r1.o];
    [((java_lang_SecurityManager*) _r3.o) checkPermission___java_security_Permission:_r0.o];
    label43:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    [_ex release];
    return;
}
- (void) checkPackageDefinition___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r3.o = self;
    _r4.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    [_r4.o retain];
    if (_r4.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    [_r0.o release];
    _r0.o = @"package.definition";
    _r5.i = [java_lang_SecurityManager checkPackageProperty___java_lang_String_java_lang_String:_r0.o:_r4.o];
    if (_r5.i == 0) goto label43;
    [_r0.o release];
    _r0.o = [[java_lang_RuntimePermission alloc] init];
    _r1.o = [[java_lang_StringBuilder alloc] init];
    [((java_lang_StringBuilder*) _r1.o) __init_java_lang_StringBuilder__];
    _r2.o = @"defineClassInPackage.";
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___java_lang_String:_r2.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) append___java_lang_String:_r4.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r1.o;
    _r1.o = [((java_lang_StringBuilder*) _r1.o) toString__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [((java_lang_RuntimePermission*) _r0.o) __init_java_lang_RuntimePermission___java_lang_String:_r1.o];
    [((java_lang_SecurityManager*) _r3.o) checkPermission___java_security_Permission:_r0.o];
    label43:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    [_ex release];
    return;
}
+ (int) checkPackageProperty___java_lang_String_java_lang_String :(java_lang_String*)n1 :(java_lang_String*)n2
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    XMLVMElem _r9;
    XMLVMElem _r10;
    XMLVMElem _r11;
    XMLVMElem _r12;
    XMLVMElem _r13;
    _r11.o = n1;
    _r12.o = n2;
    _r0.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    _r6.o = JAVA_NULL;
    _r7.o = JAVA_NULL;
    _r8.o = JAVA_NULL;
    [_r11.o retain];
    [_r12.o retain];
    _r10.i = 46;
    _r9.i = 1;
//    _r8.o = [org_apache_harmony_luni_util_PriviAction getSecurityProperty___java_lang_String:_r11.o];
    _r3.o = [java_security_AccessController doPrivileged___java_security_PrivilegedAction:_r8.o];
    _r3.o = _r3.o;
    if (_r3.o == JAVA_NULL) goto label93;
    _r4.i = [((java_lang_String*) _r12.o) length__];
//    [_r8.o release];
    _r8.o = @", *";
    _r7.o = [((java_lang_String*) _r3.o) split___java_lang_String:_r8.o];
    _r0 = _r7;
    [_r0.o retain];
    _r2.i = [_r0.o count];
    _r1.i = 0;
    label28:;
    if (_r1.i >= _r2.i) goto label93;
    [_r6.o release];
    _r6.o = ((XMLVMArray*) _r0.o)->array.o[_r1.i];
    [_r6.o retain];
    _r5.i = [((java_lang_String*) _r6.o) length__];
    if (_r4.i <= _r5.i) goto label60;
    _r13.i = [((java_lang_String*) _r12.o) startsWith___java_lang_String:_r6.o];
    if (_r13.i == 0) goto label60;
    _r13.i = _r5.i - _r9.i;
    _r13.i = [((java_lang_String*) _r6.o) charAt___int:_r13.i];
    if (_r13.i == _r10.i) goto label58;
    _r13.i = [((java_lang_String*) _r12.o) charAt___int:_r5.i];
    if (_r13.i != _r10.i) goto label60;
    label58:;
    _r13 = _r9;
    label59:;
    [_r0.o release];
    [_r3.o release];
    [_r6.o release];
    [_r7.o release];
    [_r8.o release];
    [_r11.o release];
    [_r12.o release];
    return _r13.i;
    label60:;
    if (_r4.i != _r5.i) goto label70;
    _r13.i = [((java_lang_String*) _r6.o) startsWith___java_lang_String:_r12.o];
    if (_r13.i == 0) goto label70;
    _r13 = _r9;
    goto label59;
    label70:;
    _r13.i = _r4.i + 1;
    if (_r13.i != _r5.i) goto label90;
    _r13.i = [((java_lang_String*) _r6.o) startsWith___java_lang_String:_r12.o];
    if (_r13.i == 0) goto label90;
    _r13.i = _r5.i - _r9.i;
    _r13.i = [((java_lang_String*) _r6.o) charAt___int:_r13.i];
    if (_r13.i != _r10.i) goto label90;
    _r13 = _r9;
    goto label59;
    label90:;
    _r1.i = _r1.i + 1;
    goto label28;
    label93:;
    _r13.i = 0;
    goto label59;
}
- (void) checkPropertiesAccess__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = [java_lang_SecurityManager _GET_READ_WRITE_ALL_PROPERTIES_PERMISSION];
    [_r0.o retain];
    [((java_lang_SecurityManager*) _r1.o) checkPermission___java_security_Permission:_r0.o];
    [_r0.o release];
    [_r1.o release];
    return;
}
- (void) checkPropertyAccess___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r2.o = self;
    _r3.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r2.o retain];
    [_r3.o retain];
    _r0.o = [[java_util_PropertyPermission alloc] init];
    _r1.o = @"read";
    [((java_util_PropertyPermission*) _r0.o) __init_java_util_PropertyPermission___java_lang_String_java_lang_String:_r3.o:_r1.o];
    [((java_lang_SecurityManager*) _r2.o) checkPermission___java_security_Permission:_r0.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    return;
}
- (void) checkRead___java_io_FileDescriptor :(java_io_FileDescriptor*)n1
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    if (_r2.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_ex release];
    return;
}
- (void) checkRead___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r2.o = self;
    _r3.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r2.o retain];
    [_r3.o retain];
    _r0.o = [[java_io_FilePermission alloc] init];
    _r1.o = @"read";
    [((java_io_FilePermission*) _r0.o) __init_java_io_FilePermission___java_lang_String_java_lang_String:_r3.o:_r1.o];
    [((java_lang_SecurityManager*) _r2.o) checkPermission___java_security_Permission:_r0.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    return;
}
- (void) checkRead___java_lang_String_java_lang_Object :(java_lang_String*)n1 :(java_lang_Object*)n2
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    _r2.o = self;
    _r3.o = n1;
    _r4.o = n2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r2.o retain];
    [_r3.o retain];
    [_r4.o retain];
    _r0.o = [[java_io_FilePermission alloc] init];
    _r1.o = @"read";
    [((java_io_FilePermission*) _r0.o) __init_java_io_FilePermission___java_lang_String_java_lang_String:_r3.o:_r1.o];
    [((java_lang_SecurityManager*) _r2.o) checkPermission___java_security_Permission_java_lang_Object:_r0.o:_r4.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r4.o release];
    return;
}
- (void) checkSecurityAccess___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    _r0.o = [[java_security_SecurityPermission alloc] init];
    [((java_security_SecurityPermission*) _r0.o) __init_java_security_SecurityPermission___java_lang_String:_r2.o];
    [((java_lang_SecurityManager*) _r1.o) checkPermission___java_security_Permission:_r0.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    return;
}
- (void) checkSetFactory__
{
    XMLVMElem _r0;
    _r0.o = self;
    [_r0.o retain];
    [_r0.o release];
    return;
}
- (int) checkTopLevelWindow___java_lang_Object :(java_lang_Object*)n1
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    XMLVMElem _r9;
    XMLVMElem _r10;
    _r9.o = self;
    _r10.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    _r4.o = JAVA_NULL;
    _r6.o = JAVA_NULL;
    [_r9.o retain];
    [_r10.o retain];
    _r8.i = 1;
    _r7.i = 0;
    if (_r10.o != JAVA_NULL) goto label10;
    _r4.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r4.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r4.o;
   _r4.o = JAVA_NULL;
    @throw _ex;
      label10:;
    @try {
    [_r4.o release];
    _r4.o = @"java.awt.AWTPermission";
    _r0.o = [java_lang_Class forName___java_lang_String:_r4.o];
    [_r4.o release];
    _r4.i = 1;
    _r4.o = [XMLVMArray createSingleDimensionWithType:0 andSize:_r4.i];
    _r5.i = 0;
    _r6.o = [java_lang_String getClass__];
    [((XMLVMArray*) _r4.o)->array.o[_r5.i] release];
    ((XMLVMArray*) _r4.o)->array.o[_r5.i] = _r6.o;
    [_r6.o retain];
    _r1.o = [((java_lang_Class*) _r0.o) getConstructor___java_lang_Class_ARRAYTYPE:_r4.o];
    [_r4.o release];
    _r4.i = 1;
    _r4.o = [XMLVMArray createSingleDimensionWithType:0 andSize:_r4.i];
    _r5.i = 0;
    [_r6.o release];
    _r6.o = @"showWindowWithoutWarningBanner";
    [((XMLVMArray*) _r4.o)->array.o[_r5.i] release];
    ((XMLVMArray*) _r4.o)->array.o[_r5.i] = _r6.o;
    [_r6.o retain];
    _r3.o = [((java_lang_reflect_Constructor*) _r1.o) newInstance___java_lang_Object_ARRAYTYPE:_r4.o];
    _r3.o = _r3.o;
    [((java_lang_SecurityManager*) _r9.o) checkPermission___java_security_Permission:_r3.o];
}
    @catch (java_lang_ClassNotFoundException* ex) {
        _ex = ex;
        goto label59;
    }
    @catch (java_lang_NoSuchMethodException* ex) {
        _ex = ex;
        goto label57;
    }
    @catch (java_lang_InstantiationException* ex) {
        _ex = ex;
        goto label55;
    }
    @catch (java_lang_IllegalAccessException* ex) {
        _ex = ex;
        goto label53;
    }
    @catch (java_lang_reflect_InvocationTargetException* ex) {
        _ex = ex;
        goto label51;
    }
    @catch (java_lang_SecurityException* ex) {
        _ex = ex;
        goto label47;
    }
    label45:;
    [_r4.o release];
    _r4 = _r8;
    label46:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r6.o release];
    [_r9.o release];
    [_r10.o release];
    [_ex release];
    return _r4.i;
    label47:;
    [_r4.o release];
    _r4.o = _ex; _ex = JAVA_NULL;
    _r2 = _r4;
    [_r2.o retain];
    [_r4.o release];
    _r4 = _r7;
    goto label46;
    label51:;
    [_r4.o release];
    _r4.o = _ex; _ex = JAVA_NULL;
    goto label45;
    label53:;
    [_r4.o release];
    _r4.o = _ex; _ex = JAVA_NULL;
    goto label45;
    label55:;
    [_r4.o release];
    _r4.o = _ex; _ex = JAVA_NULL;
    goto label45;
    label57:;
    [_r4.o release];
    _r4.o = _ex; _ex = JAVA_NULL;
    goto label45;
    label59:;
    [_r4.o release];
    _r4.o = _ex; _ex = JAVA_NULL;
    goto label45;
}
- (void) checkSystemClipboardAccess__
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    _r6.o = self;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    _r5.o = JAVA_NULL;
    [_r6.o retain];
    @try {
    _r3.o = @"java.awt.AWTPermission";
    _r0.o = [java_lang_Class forName___java_lang_String:_r3.o];
    [_r3.o release];
    _r3.i = 1;
    _r3.o = [XMLVMArray createSingleDimensionWithType:0 andSize:_r3.i];
    _r4.i = 0;
    _r5.o = [java_lang_String getClass__];
    [((XMLVMArray*) _r3.o)->array.o[_r4.i] release];
    ((XMLVMArray*) _r3.o)->array.o[_r4.i] = _r5.o;
    [_r5.o retain];
    _r1.o = [((java_lang_Class*) _r0.o) getConstructor___java_lang_Class_ARRAYTYPE:_r3.o];
    [_r3.o release];
    _r3.i = 1;
    _r3.o = [XMLVMArray createSingleDimensionWithType:0 andSize:_r3.i];
    _r4.i = 0;
    [_r5.o release];
    _r5.o = @"accessClipboard";
    [((XMLVMArray*) _r3.o)->array.o[_r4.i] release];
    ((XMLVMArray*) _r3.o)->array.o[_r4.i] = _r5.o;
    [_r5.o retain];
    _r2.o = [((java_lang_reflect_Constructor*) _r1.o) newInstance___java_lang_Object_ARRAYTYPE:_r3.o];
    _r2.o = _r2.o;
    [((java_lang_SecurityManager*) _r6.o) checkPermission___java_security_Permission:_r2.o];
}
    @catch (java_lang_ClassNotFoundException* ex) {
        _ex = ex;
        goto label49;
    }
    @catch (java_lang_NoSuchMethodException* ex) {
        _ex = ex;
        goto label47;
    }
    @catch (java_lang_InstantiationException* ex) {
        _ex = ex;
        goto label45;
    }
    @catch (java_lang_IllegalAccessException* ex) {
        _ex = ex;
        goto label43;
    }
    @catch (java_lang_reflect_InvocationTargetException* ex) {
        _ex = ex;
        goto label36;
    }
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r5.o release];
    [_r6.o release];
    [_ex release];
    return;
    label36:;
    _r3.o = _ex; _ex = JAVA_NULL;
    label37:;
    [_r3.o release];
    _r3.o = [[java_lang_SecurityException alloc] init];
    [((java_lang_SecurityException*) _r3.o) __init_java_lang_SecurityException__];
    [_ex release];
    _ex = _r3.o;
   _r3.o = JAVA_NULL;
    @throw _ex;
      label43:;
    [_r3.o release];
    _r3.o = _ex; _ex = JAVA_NULL;
    goto label37;
    label45:;
    _r3.o = _ex; _ex = JAVA_NULL;
    goto label37;
    label47:;
    _r3.o = _ex; _ex = JAVA_NULL;
    goto label37;
    label49:;
    _r3.o = _ex; _ex = JAVA_NULL;
    goto label37;
}
- (void) checkAwtEventQueueAccess__
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    _r6.o = self;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r3.o = JAVA_NULL;
    _r5.o = JAVA_NULL;
    [_r6.o retain];
    @try {
    _r3.o = @"java.awt.AWTPermission";
    _r0.o = [java_lang_Class forName___java_lang_String:_r3.o];
    [_r3.o release];
    _r3.i = 1;
    _r3.o = [XMLVMArray createSingleDimensionWithType:0 andSize:_r3.i];
    _r4.i = 0;
    _r5.o = [java_lang_String getClass__];
    [((XMLVMArray*) _r3.o)->array.o[_r4.i] release];
    ((XMLVMArray*) _r3.o)->array.o[_r4.i] = _r5.o;
    [_r5.o retain];
    _r1.o = [((java_lang_Class*) _r0.o) getConstructor___java_lang_Class_ARRAYTYPE:_r3.o];
    [_r3.o release];
    _r3.i = 1;
    _r3.o = [XMLVMArray createSingleDimensionWithType:0 andSize:_r3.i];
    _r4.i = 0;
    [_r5.o release];
    _r5.o = @"accessEventQueue";
    [((XMLVMArray*) _r3.o)->array.o[_r4.i] release];
    ((XMLVMArray*) _r3.o)->array.o[_r4.i] = _r5.o;
    [_r5.o retain];
    _r2.o = [((java_lang_reflect_Constructor*) _r1.o) newInstance___java_lang_Object_ARRAYTYPE:_r3.o];
    _r2.o = _r2.o;
    [((java_lang_SecurityManager*) _r6.o) checkPermission___java_security_Permission:_r2.o];
}
    @catch (java_lang_ClassNotFoundException* ex) {
        _ex = ex;
        goto label49;
    }
    @catch (java_lang_NoSuchMethodException* ex) {
        _ex = ex;
        goto label47;
    }
    @catch (java_lang_InstantiationException* ex) {
        _ex = ex;
        goto label45;
    }
    @catch (java_lang_IllegalAccessException* ex) {
        _ex = ex;
        goto label43;
    }
    @catch (java_lang_reflect_InvocationTargetException* ex) {
        _ex = ex;
        goto label36;
    }
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_r5.o release];
    [_r6.o release];
    [_ex release];
    return;
    label36:;
    _r3.o = _ex; _ex = JAVA_NULL;
    label37:;
    [_r3.o release];
    _r3.o = [[java_lang_SecurityException alloc] init];
    [((java_lang_SecurityException*) _r3.o) __init_java_lang_SecurityException__];
    [_ex release];
    _ex = _r3.o;
   _r3.o = JAVA_NULL;
    @throw _ex;
      label43:;
    [_r3.o release];
    _r3.o = _ex; _ex = JAVA_NULL;
    goto label37;
    label45:;
    _r3.o = _ex; _ex = JAVA_NULL;
    goto label37;
    label47:;
    _r3.o = _ex; _ex = JAVA_NULL;
    goto label37;
    label49:;
    _r3.o = _ex; _ex = JAVA_NULL;
    goto label37;
}
- (void) checkPrintJobAccess__
{
    XMLVMElem _r0;
    _r0.o = self;
    [_r0.o retain];
    [_r0.o release];
    return;
}
- (void) checkWrite___java_io_FileDescriptor :(java_io_FileDescriptor*)n1
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r1.o = self;
    _r2.o = n1;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    [_r2.o retain];
    if (_r2.o != JAVA_NULL) goto label8;
    _r0.o = [[java_lang_NullPointerException alloc] init];
    [((java_lang_NullPointerException*) _r0.o) __init_java_lang_NullPointerException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label8:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_ex release];
    return;
}
- (void) checkWrite___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r2.o = self;
    _r3.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    [_r2.o retain];
    [_r3.o retain];
    _r0.o = [[java_io_FilePermission alloc] init];
    _r1.o = @"write";
    [((java_io_FilePermission*) _r0.o) __init_java_io_FilePermission___java_lang_String_java_lang_String:_r3.o:_r1.o];
    [((java_lang_SecurityManager*) _r2.o) checkPermission___java_security_Permission:_r0.o];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    return;
}
- (int) getInCheck__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    [_r1.o retain];
    _r0.i = ((java_lang_SecurityManager*) _r1.o)->inCheck_boolean;
    [_r1.o release];
    return _r0.i;
}
- (XMLVMArray*) getClassContext__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r2.o = self;
    _r0.o = JAVA_NULL;
    [_r2.o retain];
    _r0.i = -1;
    _r1.i = 0;
    _r0.o = [java_lang_Class getStackClasses___int_boolean:_r0.i:_r1.i];
    [_r2.o release];
    return _r0.o;
}
- (java_lang_ClassLoader*) currentClassLoader__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    return _r0.o;
}
- (int) classLoaderDepth__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    [_r1.o retain];
    _r0.i = -1;
    [_r1.o release];
    return _r0.i;
}
- (java_lang_Class*) currentLoadedClass__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = JAVA_NULL;
    [_r1.o release];
    return _r0.o;
}
- (int) classDepth___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    _r4.o = self;
    _r5.o = n1;
    _r0.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r4.o retain];
    [_r5.o retain];
    _r3.i = -1;
    _r2.i = 0;
    _r0.o = [java_lang_Class getStackClasses___int_boolean:_r3.i:_r2.i];
    _r1.i = 0;
    label7:;
    _r2.i = [_r0.o count];
    if (_r1.i >= _r2.i) goto label27;
    _r2.o = ((XMLVMArray*) _r0.o)->array.o[_r1.i];
    [_r2.o retain];
    _rtmp.o =  _r2.o;
    _r2.o = [((java_lang_Class*) _r2.o) getName__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r2.o;
    _r2.i = [((java_lang_String*) _r2.o) equals___java_lang_Object:_r5.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    if (_r2.i == 0) goto label24;
    _r2 = _r1;
    label23:;
    [_r0.o release];
    [_r4.o release];
    [_r5.o release];
    return _r2.i;
    label24:;
    _r1.i = _r1.i + 1;
    goto label7;
    label27:;
    _r2 = _r3;
    goto label23;
}
- (int) inClass___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r2.o = self;
    _r3.o = n1;
    [_r2.o retain];
    [_r3.o retain];
    _r0.i = [((java_lang_SecurityManager*) _r2.o) classDepth___java_lang_String:_r3.o];
    _r1.i = -1;
    if (_r0.i == _r1.i) goto label9;
    _r0.i = 1;
    label8:;
    [_r2.o release];
    [_r3.o release];
    return _r0.i;
    label9:;
    _r0.i = 0;
    goto label8;
}
- (int) inClassLoader__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = [((java_lang_SecurityManager*) _r1.o) currentClassLoader__];
    if (_r0.o == JAVA_NULL) goto label8;
    [_r0.o release];
    _r0.i = 1;
    label7:;
    [_r1.o release];
    return _r0.i;
    label8:;
    [_r0.o release];
    _r0.i = 0;
    goto label7;
}
- (java_lang_ThreadGroup*) getThreadGroup__
{
    XMLVMElem _rtmp;
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = [java_lang_Thread currentThread__];
    _rtmp.o =  _r0.o;
    _r0.o = [((java_lang_Thread*) _r0.o) getThreadGroup__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r1.o release];
    return _r0.o;
}
- (java_lang_Object*) getSecurityContext__
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r1.o = self;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = [java_security_AccessController getContext__];
    [_r1.o release];
    return _r0.o;
}
- (void) checkPermission___java_security_Permission :(java_security_Permission*)n1
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    _r0.o = self;
    _r1.o = n1;
    [_r0.o retain];
    [_r1.o retain];
    [_r0.o release];
    [_r1.o release];
    return;
}
- (void) checkPermission___java_security_Permission_java_lang_Object :(java_security_Permission*)n1 :(java_lang_Object*)n2
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r0.o = self;
    _r1.o = n1;
    _r2.o = n2;
    [_r0.o retain];
    [_r1.o retain];
    [_r2.o retain];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    return;
}
+ (void) __clinit_java_lang_SecurityManager
{
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r0.o = [[java_util_PropertyPermission alloc] init];
    _r1.o = @"*";
    _r2.o = @"read,write";
    [((java_util_PropertyPermission*) _r0.o) __init_java_util_PropertyPermission___java_lang_String_java_lang_String:_r1.o:_r2.o];
    [java_lang_SecurityManager _RELEASE_READ_WRITE_ALL_PROPERTIES_PERMISSION];
    [java_lang_SecurityManager _PUT_READ_WRITE_ALL_PROPERTIES_PERMISSION: _r0.o];
    [_r0.o retain];
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    return;
}

@end

