#import "java_io_PrintStream.h"
#import "java_lang_Float.h"
#import "java_lang_Integer.h"
#import "java_lang_RuntimeException.h"
#import "java_lang_String.h"
#import "java_lang_StringBuilder.h"
#import "java_lang_System.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "pkg_BitwiseConversion.h"
#import "org_xmlvm_iphone_NSObject.h"


@implementation pkg_BitwiseConversion;

+ (void) initialize
{
    if (strcmp(class_getName(self), "pkg_BitwiseConversion") == 0) {
    }
}

- (id) init
{
    if (self = [super init]) {
    }
    return self;
}

- (void) dealloc
{
    if (strcmp(object_getClassName(self), "pkg_BitwiseConversion") == 0) {
        [self dealloc__];
    }
    [super dealloc];
}

- (void) __init_pkg_BitwiseConversion__
{
    XMLVMElem _r0;
    _r0.o = self;
    [_r0.o retain];
    [((java_lang_Object*) _r0.o) __init_java_lang_Object__];
    [_r0.o release];
    return;
}
+ (int) testNanCase___int :(int)n1
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    XMLVMElem _r9;
    XMLVMElem _r10;
    XMLVMElem _r11;
    XMLVMElem _r12;
    XMLVMElem _r13;
    XMLVMElem _r14;
    XMLVMElem _r15;
    XMLVMElem _r16;
    _r11.i = n1;
    _r1.o = JAVA_NULL;
    _r7.o = JAVA_NULL;
    _r8.o = JAVA_NULL;
    _r12.o = JAVA_NULL;
    _r13.o = JAVA_NULL;
    _r14.o = JAVA_NULL;
    _r15.o = JAVA_NULL;
    _r16.o = JAVA_NULL;
    _r10.i = 1;
    _r9.i = 0;
    _r0.i = 8388607;
    _r0.i = _r0.i & _r11.i;
    _r1.i = 2;
    _r1.o = [XMLVMArray createSingleDimensionWithType:6 andSize:_r1.i];
    _r2.i = 2139095040;
    _r2.i = _r2.i | _r0.i;
    _r2.f = [java_lang_Float intBitsToFloat___int:_r2.i];
    ((XMLVMArray*) _r1.o)->array.f[_r9.i] = _r2.f;
    _r2.i = -8388608;
    _r2.i = _r2.i | _r0.i;
    _r2.f = [java_lang_Float intBitsToFloat___int:_r2.i];
    ((XMLVMArray*) _r1.o)->array.f[_r10.i] = _r2.f;
    _r2.i = [_r1.o count];
    _r3 = _r9;
    _r4 = _r9;
    label30:;
    if (_r3.i >= _r2.i) goto label103;
    _r5.f = ((XMLVMArray*) _r1.o)->array.f[_r3.i];
    _r6.i = [java_lang_Float isNaN___float:_r5.f];
    if (_r6.i != 0) goto label75;
    [_r1.o release];
    _r1.o = [[java_lang_RuntimeException alloc] init];
    [_r13.o release];
    _r13.o = [[java_lang_StringBuilder alloc] init];
    [((java_lang_StringBuilder*) _r13.o) __init_java_lang_StringBuilder__];
    [_r14.o release];
    _r14.o = @"Invalid input ";
    _rtmp.o =  _r13.o;
    _r13.o = [((java_lang_StringBuilder*) _r13.o) append___java_lang_String:_r14.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r12.o release];
    _r12.o = [((java_lang_StringBuilder*) _r13.o) append___int:_r0.i];
    [_r13.o release];
    _r13.o = @"yielded non-NaN";
    _rtmp.o =  _r12.o;
    _r12.o = [((java_lang_StringBuilder*) _r12.o) append___java_lang_String:_r13.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r12.o;
    _r12.o = [((java_lang_StringBuilder*) _r12.o) append___float:_r5.f];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r12.o;
    _r12.o = [((java_lang_StringBuilder*) _r12.o) toString__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [((java_lang_RuntimeException*) _r1.o) __init_java_lang_RuntimeException___java_lang_String:_r12.o];
    [_ex release];
    _ex = _r1.o;
   _r1.o = JAVA_NULL;
    @throw _ex;
      label75:;
    _r5.i = [java_lang_Float floatToIntBits___float:_r5.f];
    _r6.i = 2143289344;
    if (_r5.i == _r6.i) goto label100;
    _r4.i = _r4.i + 1;
    [_r16.o release];
    _r16.o = [java_lang_System _GET_err];
    [_r16.o retain];
    [_r7.o release];
    _r7.o = @"Non-canoncial NaN bits returned: %x%n";
    [_r8.o release];
    _r8.o = [XMLVMArray createSingleDimensionWithType:0 andSize:_r10.i];
    [_r15.o release];
    _r15.o = [java_lang_Integer valueOf___int:_r5.i];
    [((XMLVMArray*) _r8.o)->array.o[_r9.i] release];
    ((XMLVMArray*) _r8.o)->array.o[_r9.i] = _r15.o;
    [_r15.o retain];
    _rtmp.o = [((java_io_PrintStream*) _r16.o) format___java_lang_String_java_lang_Object_ARRAYTYPE:_r7.o:_r8.o];
    [_rtmp.o release];
    label100:;
    _r3.i = _r3.i + 1;
    goto label30;
    label103:;
    [_r1.o release];
    [_r7.o release];
    [_r8.o release];
    [_r12.o release];
    [_r13.o release];
    [_r14.o release];
    [_r15.o release];
    [_r16.o release];
    [_ex release];
    return _r4.i;
}
+ (void) testmain___java_lang_String_ARRAYTYPE :(XMLVMArray*)n1
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    _r3.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r3.o retain];
    _r4.i = 0;
    _r5 = _r4;
    label2:;
    _r6.i = 23;
    if (_r4.i >= _r6.i) goto label16;
    _r6.i = 1;
    _r6.i = _r6.i << _r4.i;
    _r6.i = [pkg_BitwiseConversion testNanCase___int:_r6.i];
    _r5.i = _r5.i + _r6.i;
    _r4.i = _r4.i + 1;
    goto label2;
    label16:;
    _r4.f = Infinity;
    _r4.i = [java_lang_Float floatToIntBits___float:_r4.f];
    _r6.i = Infinity;// 2139095040;
    if (_r4.i == _r6.i) goto label63;
    _r4.i = _r5.i + 1;
    _r1.o = [java_lang_System _GET_err];
    [_r1.o retain];
    _r2.o = @"Bad conversion for +infinity.";
    [((java_io_PrintStream*) _r1.o) println___java_lang_String:_r2.o];
    label35:;
    _r5.f = -Infinity;
    _r5.i = [java_lang_Float floatToIntBits___float:_r5.f];
    _r6.i = -Infinity;//-8388608;
    if (_r5.i == _r6.i) goto label54;
    _r4.i = _r4.i + 1;
    [_r1.o release];
    _r1.o = [java_lang_System _GET_err];
    [_r1.o retain];
    [_r2.o release];
    _r2.o = @"Bad conversion for -infinity.";
    [((java_io_PrintStream*) _r1.o) println___java_lang_String:_r2.o];
    label54:;
    if (_r5.i <= 0) goto label62;//if (_r4.i <= 0) goto label62;
    _r0.o = [[java_lang_RuntimeException alloc] init];
    [((java_lang_RuntimeException*) _r0.o) __init_java_lang_RuntimeException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label62:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r3.o release];
    [_ex release];
    return;
    label63:;
    _r4 = _r5;
    goto label35;
}

@end

