#import "java_io_PrintStream.h"
#import "java_lang_Class.h"
#import "java_lang_Exception.h"
#import "java_lang_RuntimeException.h"
#import "java_lang_String.h"
#import "java_lang_StringBuilder.h"
#import "java_lang_System.h"
#import "pkg_BitwiseConversion.h"
#import "pkg_Constants.h"
#import "pkg_Extrema.h"
#import "pkg_NaNInfinityParsing.h"
#import "pkg_ParseFloat.h"
#import "Foundation/NSException.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "pkg_Main.h"
#import "org_xmlvm_iphone_NSObject.h"


@implementation pkg_Main;

+ (void) initialize
{
}

- (id) init
{
}

- (void) dealloc
{
}

- (void) __init_pkg_Main__
{
}

+ (void) main___java_lang_String_ARRAYTYPE :(XMLVMArray*)n1;
{
}

@end

int main(int argc, char* argv[])
{
    @try {
      [pkg_BitwiseConversion testmain___java_lang_String_ARRAYTYPE: JAVA_NULL];
      NSLog(@"BitwiseConversion PASS");
    } @catch (NSException* e) {
      NSLog(@"BitwiseConversion FAIL - %@", [e reason]);
    }
    
    @try {
      [pkg_Constants testmain___java_lang_String_ARRAYTYPE: JAVA_NULL];
      NSLog(@"Constants PASS");
    } @catch (NSException* e) {
      NSLog(@"Constants FAIL - %@", e);
    }
    
    @try {
      [pkg_Extrema testmain___java_lang_String_ARRAYTYPE: JAVA_NULL];
      NSLog(@"Extrema PASS");
    } @catch (NSException* e) {
      NSLog(@"Extrema FAIL - %@", e);
    }
    
    @try {
      [pkg_NaNInfinityParsing testmain___java_lang_String_ARRAYTYPE: JAVA_NULL];
      NSLog(@"NaNInfinityParsing PASS");
    } @catch (NSException* e) {
      NSLog(@"NaNInfinityParsing FAIL - %@", e);
    }
    
    @try {
      [pkg_ParseFloat testmain___java_lang_String_ARRAYTYPE: JAVA_NULL];
      NSLog(@"ParseFloat PASS");
    } @catch (NSException* e) {
      NSLog(@"ParseFloat FAIL - %@", e);
    }
    
}
  
  
