#import "java_io_PrintStream.h"
#import "java_lang_Double.h"
#import "java_lang_Long.h"
#import "java_lang_RuntimeException.h"
#import "java_lang_String.h"
#import "java_lang_StringBuilder.h"
#import "java_lang_System.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "pkg_BitwiseConversion.h"
#import "org_xmlvm_iphone_NSObject.h"


@implementation pkg_BitwiseConversion;

+ (void) initialize
{
    if (strcmp(class_getName(self), "pkg_BitwiseConversion") == 0) {
    }
}

- (id) init
{
    if (self = [super init]) {
    }
    return self;
}

- (void) dealloc
{
    if (strcmp(object_getClassName(self), "pkg_BitwiseConversion") == 0) {
        [self dealloc__];
    }
    [super dealloc];
}

- (void) __init_pkg_BitwiseConversion__
{
    XMLVMElem _r0;
    _r0.o = self;
    [_r0.o retain];
    [((java_lang_Object*) _r0.o) __init_java_lang_Object__];
    [_r0.o release];
    return;
}
+ (int) testNanCase___long :(JAVA_LONG)n1
{
    XMLVMElem _rtmp;
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r5;
    XMLVMElem _r6;
    XMLVMElem _r8;
    XMLVMElem _r9;
    XMLVMElem _r10;
    XMLVMElem _r11;
    XMLVMElem _r12;
    XMLVMElem _r13;
    XMLVMElem _r15;
    XMLVMElem _r16;
    XMLVMElem _r17;
    XMLVMElem _r18;
    XMLVMElem _r19;
    _r13.l = n1;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    _r9.o = JAVA_NULL;
    _r10.o = JAVA_NULL;
    _r15.o = JAVA_NULL;
    _r16.o = JAVA_NULL;
    _r17.o = JAVA_NULL;
    _r18.o = JAVA_NULL;
    _r19.o = JAVA_NULL;
    _r12.i = 1;
    _r11.i = 0;
    _r0.l = 4503599627370495;
    _r0.l = _r0.l & _r13.l;
    _r2.i = 2;
    _r2.o = [XMLVMArray createSingleDimensionWithType:7 andSize:_r2.i];
    _r3.l = 9218868437227405312;
    _r3.l = _r3.l | _r0.l;
    _r3.d = [java_lang_Double longBitsToDouble___long:_r3.l];
    ((XMLVMArray*) _r2.o)->array.d[_r11.i] = _r3.d;
    _r3.l = -4503599627370496;
    _r3.l = _r3.l | _r0.l;
    _r3.d = [java_lang_Double longBitsToDouble___long:_r3.l];
    ((XMLVMArray*) _r2.o)->array.d[_r12.i] = _r3.d;
    _r3.i = [_r2.o count];
    _r4 = _r11;
    _r5 = _r11;
    label32:;
    if (_r4.i >= _r3.i) goto label107;
    _r6.d = ((XMLVMArray*) _r2.o)->array.d[_r4.i];
    _r8.i = [java_lang_Double isNaN___double:_r6.d];
    if (_r8.i != 0) goto label77;
    [_r2.o release];
    _r2.o = [[java_lang_RuntimeException alloc] init];
    [_r16.o release];
    _r16.o = [[java_lang_StringBuilder alloc] init];
    [((java_lang_StringBuilder*) _r16.o) __init_java_lang_StringBuilder__];
    [_r17.o release];
    _r17.o = @"Invalid input ";
    _rtmp.o =  _r16.o;
    _r16.o = [((java_lang_StringBuilder*) _r16.o) append___java_lang_String:_r17.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [_r15.o release];
    _r15.o = [((java_lang_StringBuilder*) _r16.o) append___long:_r0.l];
    [_r1.o release];
    _r1.o = @"yielded non-NaN";
    _rtmp.o =  _r15.o;
    _r15.o = [((java_lang_StringBuilder*) _r15.o) append___java_lang_String:_r1.o];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r15.o;
    _r15.o = [((java_lang_StringBuilder*) _r15.o) append___double:_r6.d];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    _rtmp.o =  _r15.o;
    _r15.o = [((java_lang_StringBuilder*) _r15.o) toString__];
    [_rtmp.o release];
    _rtmp.o = JAVA_NULL;
    [((java_lang_RuntimeException*) _r2.o) __init_java_lang_RuntimeException___java_lang_String:_r15.o];
    [_ex release];
    _ex = _r2.o;
   _r2.o = JAVA_NULL;
    @throw _ex;
      label77:;
    _r6.l = [java_lang_Double doubleToLongBits___double:_r6.d];
    _r8.l = 9221120237041090560;
    _r8.i = _r6.l > _r8.l ? 1 : (_r6.l == _r8.l ? 0 : -1);
    if (_r8.i == 0) goto label104;
    _r5.i = _r5.i + 1;
    [_r19.o release];
    _r19.o = [java_lang_System _GET_err];
    [_r19.o retain];
    [_r9.o release];
    _r9.o = @"Non-canoncial NaN bits returned: %x%n";
    [_r10.o release];
    _r10.o = [XMLVMArray createSingleDimensionWithType:0 andSize:_r12.i];
    [_r18.o release];
    _r18.o = [java_lang_Long valueOf___long:_r6.l];
    [((XMLVMArray*) _r10.o)->array.o[_r11.i] release];
    ((XMLVMArray*) _r10.o)->array.o[_r11.i] = _r18.o;
    [_r18.o retain];
    _rtmp.o = [((java_io_PrintStream*) _r19.o) format___java_lang_String_java_lang_Object_ARRAYTYPE:_r9.o:_r10.o];
    [_rtmp.o release];
    label104:;
    _r4.i = _r4.i + 1;
    goto label32;
    label107:;
    [_r1.o release];
    [_r2.o release];
    [_r9.o release];
    [_r10.o release];
    [_r15.o release];
    [_r16.o release];
    [_r17.o release];
    [_r18.o release];
    [_r19.o release];
    [_ex release];
    return _r5.i;
}
+ (void) testmain___java_lang_String_ARRAYTYPE :(XMLVMArray*)n1
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    XMLVMElem _r4;
    XMLVMElem _r6;
    XMLVMElem _r7;
    XMLVMElem _r8;
    XMLVMElem _r9;
    _r6.o = n1;
    _r0.o = JAVA_NULL;
    _r1.o = JAVA_NULL;
    _r2.o = JAVA_NULL;
    [_r6.o retain];
    _r7.i = 0;
    _r8 = _r7;
    label2:;
    _r9.i = 52;
    if (_r7.i >= _r9.i) goto label17;
    _r9.l = 1;
    _r9.l = _r9.l << (0x3f & _r7.l);
    _r9.i = [pkg_BitwiseConversion testNanCase___long:_r9.l];
    _r8.i = _r8.i + _r9.i;
    _r7.i = _r7.i + 1;
    goto label2;
    label17:;
    _r9.d = Infinity;
    _r9.l = [java_lang_Double doubleToLongBits___double:_r9.d];
    _r4.l = 9218868437227405312;
    _r7.i = _r9.l > _r4.l ? 1 : (_r9.l == _r4.l ? 0 : -1);
    if (_r7.i == 0) goto label68;
    _r7.i = _r8.i + 1;
    _r1.o = [java_lang_System _GET_err];
    [_r1.o retain];
    _r2.o = @"Bad conversion for +infinity.";
    [((java_io_PrintStream*) _r1.o) println___java_lang_String:_r2.o];
    label38:;
    _r8.d = -Infinity;
    _r8.l = [java_lang_Double doubleToLongBits___double:_r8.d];
    _r3.l = -4503599627370496;
    _r8.i = _r8.l > _r3.l ? 1 : (_r8.l == _r3.l ? 0 : -1);
    if (_r8.i == 0) goto label59;
    _r7.i = _r7.i + 1;
    [_r1.o release];
    _r1.o = [java_lang_System _GET_err];
    [_r1.o retain];
    [_r2.o release];
    _r2.o = @"Bad conversion for -infinity.";
    [((java_io_PrintStream*) _r1.o) println___java_lang_String:_r2.o];
    label59:;
    if (_r7.i <= 0) goto label67;
    _r0.o = [[java_lang_RuntimeException alloc] init];
    [((java_lang_RuntimeException*) _r0.o) __init_java_lang_RuntimeException__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
      label67:;
    [_r0.o release];
    [_r1.o release];
    [_r2.o release];
    [_r6.o release];
    [_ex release];
    return;
    label68:;
//    _r7 = _r8;
    goto label38;
}

@end

