#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_AssertionError;
@class java_lang_Class;
@class java_lang_Double;
@class java_lang_Float;
@class java_lang_Math;
@class java_lang_Object;
@class sun_misc_FpUtils;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface sun_misc_FpUtils : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
+ (double) _GET_twoToTheDoubleScaleUp;
+ (void) _PUT_twoToTheDoubleScaleUp: (double) v;
+ (double) _GET_twoToTheDoubleScaleDown;
+ (void) _PUT_twoToTheDoubleScaleDown: (double) v;
+ (int) _GET__assertionsDisabled;
+ (void) _PUT__assertionsDisabled: (int) v;
- (void) __init_sun_misc_FpUtils__;
+ (int) getExponent___double :(double)n1;
+ (int) getExponent___float :(float)n1;
+ (double) powerOfTwoD___int :(int)n1;
+ (float) powerOfTwoF___int :(int)n1;
+ (double) rawCopySign___double_double :(double)n1 :(double)n2;
+ (float) rawCopySign___float_float :(float)n1 :(float)n2;
+ (int) isFinite___double :(double)n1;
+ (int) isFinite___float :(float)n1;
+ (int) isInfinite___double :(double)n1;
+ (int) isInfinite___float :(float)n1;
+ (int) isNaN___double :(double)n1;
+ (int) isNaN___float :(float)n1;
+ (int) isUnordered___double_double :(double)n1 :(double)n2;
+ (int) isUnordered___float_float :(float)n1 :(float)n2;
+ (int) ilogb___double :(double)n1;
+ (int) ilogb___float :(float)n1;
+ (double) scalb___double_int :(double)n1 :(int)n2;
+ (double) scalb___float_int :(float)n1 :(int)n2;
+ (double) nextAfter___double_double :(double)n1 :(double)n2;
+ (float) nextAfter___float_double :(float)n1 :(double)n2;
+ (double) nextUp___double :(double)n1;
+ (float) nextUp___float :(float)n1;
+ (double) nextDown___double :(double)n1;
+ (double) nextDown___float :(float)n1;
+ (double) copySign___double_double :(double)n1 :(double)n2;
+ (float) copySign___float_float :(float)n1 :(float)n2;
+ (double) ulp___double :(double)n1;
+ (float) ulp___float :(float)n1;
+ (double) signum___double :(double)n1;
+ (float) signum___float :(float)n1;
+ (void) __clinit_sun_misc_FpUtils;

@end

