#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_Object;
@class sun_misc_DoubleConsts;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface sun_misc_DoubleConsts : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
+ (double) _GET_POSITIVE_INFINITY;
+ (void) _PUT_POSITIVE_INFINITY: (double) v;
+ (double) _GET_NEGATIVE_INFINITY;
+ (void) _PUT_NEGATIVE_INFINITY: (double) v;
+ (double) _GET_NaN;
+ (void) _PUT_NaN: (double) v;
+ (double) _GET_MAX_VALUE;
+ (void) _PUT_MAX_VALUE: (double) v;
+ (double) _GET_MIN_VALUE;
+ (void) _PUT_MIN_VALUE: (double) v;
+ (double) _GET_MIN_NORMAL;
+ (void) _PUT_MIN_NORMAL: (double) v;
+ (int) _GET_SIGNIFICAND_WIDTH;
+ (void) _PUT_SIGNIFICAND_WIDTH: (int) v;
+ (int) _GET_MAX_EXPONENT;
+ (void) _PUT_MAX_EXPONENT: (int) v;
+ (int) _GET_MIN_EXPONENT;
+ (void) _PUT_MIN_EXPONENT: (int) v;
+ (int) _GET_MIN_SUB_EXPONENT;
+ (void) _PUT_MIN_SUB_EXPONENT: (int) v;
+ (int) _GET_EXP_BIAS;
+ (void) _PUT_EXP_BIAS: (int) v;
+ (JAVA_LONG) _GET_SIGN_BIT_MASK;
+ (void) _PUT_SIGN_BIT_MASK: (JAVA_LONG) v;
+ (JAVA_LONG) _GET_EXP_BIT_MASK;
+ (void) _PUT_EXP_BIT_MASK: (JAVA_LONG) v;
+ (JAVA_LONG) _GET_SIGNIF_BIT_MASK;
+ (void) _PUT_SIGNIF_BIT_MASK: (JAVA_LONG) v;
- (void) __init_sun_misc_DoubleConsts__;
+ (void) __clinit_sun_misc_DoubleConsts;

@end

